
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'si' | 'ta';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Basic translations object - would be expanded for a full site
const translations: Record<Language, Record<string, string>> = {
  en: {
    'site.title': 'Anaesthesia Info Hub',
    'nav.home': 'Home',
    'nav.before': 'Before Surgery',
    'nav.during': 'During Surgery',
    'nav.after': 'After Surgery',
    'nav.resources': 'Resources',
    'hero.title': 'Understanding Anaesthesia: What to Expect Before, During, and After Your Surgery',
    'hero.subtitle': 'Your guide to a safe and comfortable surgical experience',
    'hero.intro': "Anaesthesia is a medical specialty that allows you to undergo surgery pain-free and safely. Today's anaesthetic techniques are carefully monitored by your anaesthetist, a trained physician dedicated to your comfort and well-being.",
    'cta.before': 'Before Surgery',
    'cta.during': 'During Surgery',
    'cta.after': 'After Surgery',
    'about.title': 'About Us',
    'about.whoTitle': 'Who We Are',
    'about.who': 'A collaborative initiative by anaesthesia and critical care teams at DGH Hambantota, to share trustworthy patient information.\nDeveloped by Dr Niroshan Sivaranjan.\nSupervisor - Dr Danushka Samarasinghe\n Mentor - Dr Hirushaka De Silva',
    'about.whyTitle': 'Our Mission',
    'about.why': 'To answer common patient questions, reduce anxiety, and promote informed consent.',
    
    // What to Expect Section on Home Page
    'whatToExpect.title': 'What to Expect',
    'whatToExpect.before.title': 'Before Surgery',
    'whatToExpect.before.description': 'Learn about pre-operative assessments, fasting requirements, and how to prepare mentally and physically for your procedure.',
    'whatToExpect.during.title': 'During Surgery',
    'whatToExpect.during.description': 'Discover different types of anaesthesia, how they work, potential complications, and the role of your anaesthesia team.',
    'whatToExpect.after.title': 'After Surgery',
    'whatToExpect.after.description': 'Find out what happens in the recovery room, common side effects, pain management strategies, and when you can resume normal activities.',
    'whatToExpect.learnMore': 'Learn more',
    
    // Before Surgery Page Translations
    'before.title': 'Before Surgery',
    'before.intro': 'Understanding what to expect before your procedure can help reduce anxiety and ensure the best possible outcome.',
    'before.qa1.question': 'What is pre-operative assessment?',
    'before.qa1.answer1': 'A pre-operative assessment is a thorough review of your medical history, physical examination, blood tests, ECG and other investigations to identify potential risks and optimize your health before anaesthesia.',
    'before.qa1.answer2': 'During this assessment, your anaesthetist will:',
    'before.qa1.list1': 'Review your medical history and previous surgeries',
    'before.qa1.list2': 'Ask about allergies and current medications',
    'before.qa1.list3': 'Perform a physical examination focused on your heart and lungs',
    'before.qa1.list4': 'Evaluate test results including blood work and ECG',
    'before.qa1.list5': 'Discuss the anaesthetic plan and answer your questions',
    'before.qa2.question': 'Why is fasting required?',
    'before.qa2.answer1': 'Fasting before surgery is essential to reduce the risk of stomach contents entering your lungs during anaesthesia, a serious complication called aspiration.',
    'before.qa2.guidelines': 'Fasting Guidelines:',
    'before.qa2.list1': 'Solids and milk: Stop 6 hours before surgery',
    'before.qa2.list2': 'Clear fluids (water, tea without milk): Stop 2 hours before surgery',
    'before.qa2.siptitle': 'Sip Till Send Program:',
    'before.qa2.siptext1': 'Many hospitals now encourage patients to drink clear fluids until 2 hours before surgery. This helps prevent dehydration and may improve your recovery. Ask your healthcare provider about the "Sip Till Send" protocol.',
    'before.qa2.siptext2': 'Learn more about Sip Till Send fasting information',
    'before.qa3.question': 'Which medications to avoid?',
    'before.qa3.answer1': 'Some medications can interfere with anaesthesia or increase surgical bleeding risk. Always inform your anaesthetist about all medications you\'re taking, including over-the-counter drugs and supplements.',
    'before.qa3.subtitle': 'Medications that may need to be stopped or adjusted include:',
    'before.qa3.list1': 'Blood thinners: Aspirin, clopidogrel, warfarin',
    'before.qa3.list2': 'NSAIDs: Ibuprofen, diclofenac',
    'before.qa3.list3': 'Herbal supplements: Ginkgo, garlic, fish oil',
    'before.qa3.important': 'Important: Never stop prescription medications without consulting your doctor or anaesthetist first.',
    'before.qa4.question': 'How to prepare mentally and physically?',
    'before.qa4.physical': 'Physical Preparation:',
    'before.qa4.plist1': 'Get a good night\'s sleep before surgery',
    'before.qa4.plist2': 'Stay hydrated until fasting time begins',
    'before.qa4.plist3': 'Follow any specific instructions from your surgical team',
    'before.qa4.plist4': 'Avoid alcohol for at least 24 hours before surgery',
    'before.qa4.plist5': 'If you smoke, try to quit or reduce smoking before surgery',
    'before.qa4.mental': 'Mental Preparation:',
    'before.qa4.mlist1': 'Ask questions during your pre-op assessment to address any concerns',
    'before.qa4.mlist2': 'Practice relaxation techniques like deep breathing or meditation',
    'before.qa4.mlist3': 'Bring comforting items to the hospital (within hospital guidelines)',
    'before.qa4.mlist4': 'Arrange for support from family or friends after discharge',
    'before.qa4.practical': 'Practical Preparations:',
    'before.qa4.prlist1': 'Arrange transport to and from the hospital',
    'before.qa4.prlist2': 'Prepare your home for your return (easy meals, comfortable recovery area)',
    'before.qa4.prlist3': 'Bring a list of your medications, allergies, and previous anaesthetic experiences',
    'before.qa4.prlist4': 'Remove jewelry, makeup, and nail polish before surgery',
    'before.qa4.prlist5': 'Follow specific instructions about bathing/showering before surgery',
    
    // During Surgery Translations
    'during.title': 'During Surgery',
    'during.intro': 'Understanding what happens during surgery and how anaesthesia works can help ease anxiety and prepare you for your procedure.',
    'during.qa1.question': 'What types of anaesthesia exist?',
    'during.qa1.general': 'General Anaesthesia (GA):',
    'during.qa1.generalDesc': 'A medication-induced state of unconsciousness. You\'ll be completely unaware and unable to feel pain during your procedure.',
    'during.qa1.generalUse': 'Typically used for: Major surgeries, procedures in body cavities, or when other types aren\'t suitable.',
    'during.qa1.spinal': 'Spinal/Epidural Anaesthesia:',
    'during.qa1.spinalDesc': 'Injection of local anaesthetic into the subarachnoid space (spinal) or epidural space to block nerve transmission below the waist.',
    'during.qa1.spinalUse': 'Typically used for: Lower body procedures, cesarean sections, hip/knee surgery.',
    'during.qa1.nerve': 'Peripheral Nerve Blocks:',
    'during.qa1.nerveDesc': 'Local anaesthetic injected near specific nerves to numb a particular area of the body.',
    'during.qa1.nerveUse': 'Typically used for: Arm, shoulder, or leg surgeries, providing targeted pain relief.',
    'during.qa1.sedation': 'Conscious Sedation (Monitored Anaesthesia Care):',
    'during.qa1.sedationDesc': 'Medications to help you relax and reduce pain while maintaining consciousness.',
    'during.qa1.sedationUse': 'Typically used for: Minor procedures, endoscopies, dental work.',
    
    'during.qa2.question': 'How does each type of anaesthesia work?',
    'during.qa2.general': 'General Anaesthesia Mechanics:',
    'during.qa2.generalDesc': 'General anaesthesia works through a combination of medications that:',
    'during.qa2.generalList1': 'Induce unconsciousness (propofol, thiopental)',
    'during.qa2.generalList2': 'Maintain unconsciousness (sevoflurane, desflurane gases)',
    'during.qa2.generalList3': 'Relax muscles (rocuronium, succinylcholine)',
    'during.qa2.generalList4': 'Block pain (fentanyl, morphine)',
    'during.qa2.generalEnd': 'These medications depress your central nervous system in a controlled manner, affecting different brain receptors to create a reversible state of unconsciousness.',
    'during.qa2.spinal': 'Spinal/Epidural Mechanics:',
    'during.qa2.spinalDesc': 'Local anaesthetic (like bupivacaine) is injected near the spinal cord:',
    'during.qa2.spinalList1': 'Spinal: Directly into the cerebrospinal fluid surrounding the spinal cord',
    'during.qa2.spinalList2': 'Epidural: Into the space just outside the spinal cord coverings',
    'during.qa2.spinalEnd': 'The medication blocks sodium channels in nerve membranes, preventing nerve impulses from traveling up the spinal cord to the brain.',
    'during.qa2.nerve': 'Peripheral Nerve Block Mechanics:',
    'during.qa2.nerveDesc': 'Using ultrasound guidance, anaesthetists inject local anaesthetic around specific nerve bundles. The medication temporarily blocks nerve transmission in that specific area without affecting consciousness.',
    'during.qa2.sedation': 'Sedation Mechanics:',
    'during.qa2.sedationDesc': 'Carefully titrated doses of medications like midazolam (a benzodiazepine) and fentanyl (an opioid) create a state of:',
    'during.qa2.sedationList1': 'Reduced anxiety',
    'during.qa2.sedationList2': 'Decreased pain sensation',
    'during.qa2.sedationList3': 'Amnesia (reduced memory of the procedure)',
    'during.qa2.sedationList4': 'Maintained consciousness and protective reflexes',
    
    'during.qa3.question': 'Risks & complications, prevention and management',
    'during.qa3.minor': 'Common Minor Effects:',
    'during.qa3.minorList1': 'Shivering (20%) - Prevented with warming blankets',
    'during.qa3.minorList2': 'Post-op nausea and vomiting (25%) - Managed with antiemetics like ondansetron',
    'during.qa3.minorList3': 'Sore throat (15%) - Minimized with gentle airway management',
    'during.qa3.minorList4': 'Headache (10%) - Treated with hydration and mild analgesics',
    'during.qa3.regional': 'Regional/Spinal Anaesthesia Risks:',
    'during.qa3.regionalList1': 'Post-dural puncture headache (1-2%) - Managed with hydration, caffeine, or epidural blood patch',
    'during.qa3.regionalList2': 'Transient neurological symptoms (0.5%) - Usually resolve with time',
    'during.qa3.regionalList3': 'Urinary retention - Temporary catheterization if needed',
    'during.qa3.serious': 'Serious but Rare Complications:',
    'during.qa3.seriousList1': 'Anaphylaxis (1 in 10,000) - Identified by monitoring and treated with epinephrine',
    'during.qa3.seriousList2': 'Malignant hyperthermia (< 1 in 50,000) - Genetic condition treated with dantrolene',
    'during.qa3.seriousList3': 'Permanent nerve injury (< 1 in 100,000) - Prevented by careful positioning and technique',
    'during.qa3.seriousList4': 'Awareness during general anaesthesia (< 1 in 1,000) - Monitored using BIS technology',
    'during.qa3.airway': 'Airway Complications:',
    'during.qa3.airwayList1': 'Difficult intubation (1-3%) - Managed with specialized equipment and techniques',
    'during.qa3.airwayList2': 'Aspiration (< 1%) - Prevented with fasting and rapid sequence induction',
    'during.qa3.airwayList3': 'Dental damage (< 0.5%) - Minimized with careful technique',
    'during.qa3.remember': 'Remember: Your anaesthetist is highly trained to prevent, detect, and manage these complications. The vast majority of anaesthetics are administered without any serious problems.',
    
    'during.qa4.question': 'Monitoring & safety measures',
    'during.qa4.standard': 'Standard Monitors (ASA Guidelines):',
    'during.qa4.standardList1': 'ECG - Monitors heart rate and rhythm',
    'during.qa4.standardList2': 'NIBP - Non-invasive blood pressure, typically measured every 3-5 minutes',
    'during.qa4.standardList3': 'SpO₂ - Oxygen saturation via pulse oximeter',
    'during.qa4.standardList4': 'ETCO₂ - End-tidal carbon dioxide to confirm proper breathing',
    'during.qa4.standardList5': 'Temperature - To detect and prevent hypothermia or hyperthermia',
    'during.qa4.advanced': 'Advanced Monitoring (as needed):',
    'during.qa4.advancedList1': 'Arterial line - For continuous blood pressure monitoring',
    'during.qa4.advancedList2': 'Central venous pressure - For complex cases or critically ill patients',
    'during.qa4.advancedList3': 'Neuromuscular blockade monitors - To ensure appropriate muscle relaxation',
    'during.qa4.advancedList4': 'BIS (Bispectral Index) - To monitor depth of anaesthesia',
    'during.qa4.targets': 'Normal Target Values:',
    'during.qa4.targetsList1': 'SpO₂: > 95%',
    'during.qa4.targetsList2': 'ETCO₂: 35-45 mmHg',
    'during.qa4.targetsList3': 'MAP (Mean Arterial Pressure): 65-90 mmHg',
    'during.qa4.targetsList4': 'Temperature: 36-37°C (97-99°F)',
    'during.qa4.safety': 'Safety Protocols:',
    'during.qa4.safetyList1': 'Pre-anaesthetic equipment checks using standardized checklists',
    'during.qa4.safetyList2': 'WHO Surgical Safety Checklist before incision',
    'during.qa4.safetyList3': 'Immediate access to emergency drugs and equipment',
    'during.qa4.safetyList4': 'Continuous visual and auditory alarms for vital sign deviations',
    'during.qa4.safetyList5': 'Capnography to confirm correct breathing tube placement',
    'during.qa4.modern': 'Modern anaesthesia monitoring has dramatically improved safety. Your vital signs are continuously displayed and monitored throughout your procedure by your anaesthesia team.',
    
    'during.qa5.question': 'Role of the anaesthetist during surgery',
    'during.qa5.intro': 'Your anaesthetist is a specially trained doctor who remains with you throughout your entire surgery, focusing exclusively on your safety and comfort.',
    'during.qa5.responsibilities': 'The anaesthetist\'s responsibilities include:',
    'during.qa5.respList1': 'Continuous assessment of vital signs, anaesthetic depth, pain control, and fluid status',
    'during.qa5.respList2': 'Dynamic medication adjustments throughout surgery based on your needs and surgical requirements',
    'during.qa5.respList3': 'Managing unexpected events like blood pressure changes, arrhythmias, or bleeding',
    'during.qa5.respList4': 'Coordinating with surgeons about timing, positioning, and special requirements',
    'during.qa5.respList5': 'Patient advocacy, ensuring your safety, dignity, and comfort at all times',
    'during.qa5.respList6': 'Making clinical decisions about blood transfusions, fluid management, and pain control',
    'during.qa5.team': 'Team Approach:',
    'during.qa5.teamDesc': 'Your anaesthetist often works with a team that may include:',
    'during.qa5.teamList1': 'Anaesthesia assistants or technicians',
    'during.qa5.teamList2': 'Nurse anaesthetists (in some countries)',
    'during.qa5.teamList3': 'Anaesthesia trainees under supervision',
    'during.qa5.think': 'Think of your anaesthetist as your personal "life functions manager" during surgery, constantly monitoring and adjusting to ensure your body\'s systems remain stable while you\'re unconscious or sedated.',
    
    // After Surgery Translations
    'after.title': 'After Surgery',
    'after.intro': 'Understanding what to expect after your procedure can help you prepare for recovery and recognize normal versus abnormal symptoms.',
    'after.qa1.question': 'What happens in the recovery room?',
    'after.qa1.intro': 'After your surgery, you\'ll be transferred to the Post-Anaesthesia Care Unit (PACU), also called the recovery room. This is a specialized area where you\'ll be closely monitored as you emerge from anaesthesia.',
    'after.qa1.expect': 'In the PACU, you can expect:',
    'after.qa1.monitoring': 'Continuous monitoring',
    'after.qa1.monitoringDesc': 'of your vital signs (blood pressure, heart rate, oxygen levels)',
    'after.qa1.nursing': 'One-to-one nursing care',
    'after.qa1.nursingDesc': 'until you\'re fully awake and stable',
    'after.qa1.assessments': 'Regular assessments',
    'after.qa1.assessmentsDesc': 'of your pain levels and administration of pain medication as needed',
    'after.qa1.oxygen': 'Oxygen therapy',
    'after.qa1.oxygenDesc': 'via a face mask or nasal prongs if required',
    'after.qa1.warming': 'Warming blankets',
    'after.qa1.warmingDesc': 'if you\'re cold or shivering',
    'after.qa1.iv': 'IV fluids',
    'after.qa1.ivDesc': 'until you\'re able to drink',
    'after.qa1.howLong': 'How long will I stay in recovery?',
    'after.qa1.timeFrame': 'Most patients stay in the PACU for 30 minutes to 2 hours, depending on:',
    'after.qa1.timeList1': 'The type of surgery and anaesthesia you received',
    'after.qa1.timeList2': 'How quickly you wake up and become stable',
    'after.qa1.timeList3': 'How well your pain and any nausea are controlled',
    'after.qa1.timeList4': 'If there were any complications during surgery',
    'after.qa1.transfer': 'You\'ll be transferred to a ward or discharged home once the recovery team is satisfied with your condition.',
    
    'after.qa2.question': 'Common post-op side effects & pain control',
    'after.qa2.sideEffects': 'Common Side Effects:',
    'after.qa2.throat': 'Sore throat',
    'after.qa2.throatDesc': '- From the breathing tube; usually resolves within 24-48 hours',
    'after.qa2.nausea': 'Nausea and vomiting',
    'after.qa2.nauseaDesc': '- Can be treated with anti-sickness medications',
    'after.qa2.dizziness': 'Dizziness',
    'after.qa2.dizzinessDesc': '- Often improves with gentle movement and hydration',
    'after.qa2.drowsiness': 'Drowsiness',
    'after.qa2.drowsinessDesc': '- Gradually improves as anaesthesia wears off',
    'after.qa2.shivering': 'Shivering',
    'after.qa2.shiveringDesc': '- Usually temporary; treated with warming blankets',
    'after.qa2.confusion': 'Confusion',
    'after.qa2.confusionDesc': '- More common in older adults; usually temporary',
    'after.qa2.painManagement': 'Pain Management Options:',
    'after.qa2.ivPain': 'IV pain medications',
    'after.qa2.ivPainDesc': '- Often opioids like morphine for immediate relief',
    'after.qa2.pca': 'Patient-Controlled Analgesia (PCA)',
    'after.qa2.pcaDesc': '- Allows you to self-administer small doses of pain medication by pressing a button',
    'after.qa2.oral': 'Oral pain medications',
    'after.qa2.oralDesc': '- Pills or liquids once you can drink fluids',
    'after.qa2.blocks': 'Regional blocks',
    'after.qa2.blocksDesc': '- May continue to provide pain relief for hours after surgery',
    'after.qa2.local': 'Local anaesthetic infiltration',
    'after.qa2.localDesc': '- Injected around the surgical site',
    'after.qa2.nonMed': 'Non-medication techniques',
    'after.qa2.nonMedDesc': '- Ice packs, positioning, relaxation techniques',
    'after.qa2.tips': 'Important Pain Management Tips:',
    'after.qa2.tipsList1': 'Don\'t wait until pain is severe before requesting pain relief',
    'after.qa2.tipsList2': 'Rate your pain on a scale from 0-10 when asked by healthcare staff',
    'after.qa2.tipsList3': 'Tell your nurses if pain medication isn\'t working or wears off quickly',
    'after.qa2.tipsList4': 'Report any unusual symptoms or side effects from pain medications',
    
    'after.qa3.question': 'When can I eat and drink?',
    'after.qa3.intro': 'Returning to eating and drinking after surgery depends on several factors including the type of surgery, anaesthesia used, and your individual recovery.',
    'after.qa3.guidelines': 'General Guidelines:',
    'after.qa3.fluids': 'Clear fluids',
    'after.qa3.fluidsDesc': '(water, apple juice) - Often allowed within 2-4 hours after fully waking from anaesthesia, once you can swallow safely',
    'after.qa3.light': 'Light foods',
    'after.qa3.lightDesc': '(crackers, toast, soup) - Usually permitted once you\'re tolerating fluids well, often 4-6 hours after surgery',
    'after.qa3.regular': 'Regular diet',
    'after.qa3.regularDesc': '- Typically resumed gradually as tolerated, often by the next day for minor surgeries',
    'after.qa3.considerations': 'Special Considerations:',
    'after.qa3.abdominal': 'Abdominal surgery',
    'after.qa3.abdominalDesc': '- May require waiting until bowel sounds return and gas or bowel movements occur',
    'after.qa3.throat': 'Throat or mouth surgery',
    'after.qa3.throatDesc': '- May require special dietary restrictions',
    'after.qa3.nausea': 'Nausea or vomiting',
    'after.qa3.nauseaDesc': '- May delay return to eating until symptoms improve',
    'after.qa3.medications': 'Some medications',
    'after.qa3.medicationsDesc': '- May need to be taken with food, affecting when you can restart them',
    'after.qa3.always': 'Always follow your healthcare provider\'s specific instructions about eating and drinking after your procedure. Start slowly and increase gradually as tolerated.',
    
    'after.qa4.question': 'Discharge instructions & follow-up',
    'after.qa4.instructions': 'Common Discharge Instructions:',
    'after.qa4.activity': 'Activity restrictions',
    'after.qa4.activityDesc': '- When you can return to normal activities, driving, work, and exercise',
    'after.qa4.wound': 'Wound care',
    'after.qa4.woundDesc': '- How to clean and dress the surgical site',
    'after.qa4.medication': 'Medication instructions',
    'after.qa4.medicationDesc': '- When and how to take prescribed medications',
    'after.qa4.infection': 'Signs of infection',
    'after.qa4.infectionDesc': '- What to watch for (increased pain, redness, swelling, discharge, fever)',
    'after.qa4.diet': 'Diet guidelines',
    'after.qa4.dietDesc': '- Any special dietary requirements during recovery',
    'after.qa4.showering': 'Showering/bathing',
    'after.qa4.showeringDesc': '- When it\'s safe to get the surgical area wet',
    'after.qa4.contact': 'Contact information',
    'after.qa4.contactDesc': '- Who to call if you have questions or problems',
    'after.qa4.appointments': 'Follow-up Appointments:',
    'after.qa4.appointmentsDesc': 'Your discharge instructions will include details about follow-up visits. Typically, you\'ll have:',
    'after.qa4.appointmentsList1': 'An appointment with your surgeon to check your healing',
    'after.qa4.appointmentsList2': 'Instructions for any suture or staple removal',
    'after.qa4.appointmentsList3': 'Information about any required physical therapy',
    'after.qa4.keepAppts': 'Be sure to keep all follow-up appointments, even if you\'re feeling well.',
    'after.qa4.seekHelp': 'When to Seek Immediate Medical Attention:',
    'after.qa4.seekList1': 'Difficulty breathing or shortness of breath',
    'after.qa4.seekList2': 'Chest pain or irregular heartbeat',
    'after.qa4.seekList3': 'Severe pain not controlled by prescribed medications',
    'after.qa4.seekList4': 'Excessive bleeding or wound drainage',
    'after.qa4.seekList5': 'Signs of infection (fever above 38°C/100.4°F, increasing redness or warmth)',
    'after.qa4.seekList6': 'Inability to urinate within 8-10 hours after surgery',
    'after.qa4.seekList7': 'Persistent nausea and vomiting',
    'after.qa4.seekList8': 'Calf pain, swelling, or redness (possible blood clot)',
    'after.qa4.pathway': 'Recovery Pathway:',
    'after.qa4.pathwayDesc': 'Your recovery will follow a general pattern, but everyone heals at their own pace. Be patient with your body and follow all medical advice to ensure the best outcome.',
    'after.qa4.keepInstructions': 'Keep your discharge instructions in an easily accessible place and bring them with you to follow-up appointments.'
  },
  si: {
    'site.title': 'නිර්වින්දනය තොරතුරු මධ්‍යස්ථානය',
    'nav.home': 'මුල් පිටුව',
    'nav.before': 'ශල්‍යකර්මයට පෙර',
    'nav.during': 'ශල්‍යකර්මය අතරතුර',
    'nav.after': 'ශල්‍යකර්මයෙන් පසු',
    'nav.resources': 'සම්පත්',
    'hero.title': 'නිර්වින්දනය ගැන අවබෝධ කර ගැනීම: ඔබේ ශල්‍යකර්මයට පෙර, අතරතුර සහ පසුව බලාපොරොත්තු විය හැකි දේ',
    'hero.subtitle': 'ආරක්ෂිත, පහසු ශල්‍යකර්ම අත්දැකීමක් සඳහා ඔබේ මාර්ගෝපදේශය',
    'hero.intro': "නිර්වින්දනය යනු ඔබට වේදනාවෙන් තොරව සහ ආරක්ෂිතව ශල්‍යකර්මයකට භාජනය වීමට ඉඩ සලසන ක්‍රමයකි. නිර්වින්දන වෛද්‍යවරයෙකු විසින් ඔබව පරික්ශා කිරීමෙන් පසුව ආරක්ශාකාරී සහ සුවපහසු ලෙස ශල්යකර්මය සිදු කිරීමට පහසුකම් සලස දෙයි.",
    'cta.before': 'ශල්‍යකර්මයට පෙර',
    'cta.during': 'ශල්‍යකර්මය අතරතුර',
    'cta.after': 'ශල්‍යකර්මයෙන් පසු',
    'about.title': 'අප ගැන',
    'about.whoTitle': 'අපි කවුද',
    'about.who': 'විශ්වාසදායක රෝගී තොරතුරු බෙදා ගැනීම සඳහා ශ්‍රී ලාංකික නිර්වින්දන හා දැඩි සත්කාර කණ්ඩායම් විසින් සිදු කරන සහයෝගී මුල පිරීමකි.',
    'about.whyTitle': 'අපේ දැක්ම',
    'about.why': 'පොදු රෝගී ප්‍රශ්න වලට පිළිතුරු දීමට, කනස්සල්ල අඩු කිරීමට සහ දැනුවත් කැමැත්ත ප්‍රවර්ධනය කිරීමට.',
    
    // What to Expect Section on Home Page - Sinhala
    'whatToExpect.title': 'බලාපොරොත්තු විය හැකි දේ',
    'whatToExpect.before.title': 'ශල්‍යකර්මයට පෙර',
    'whatToExpect.before.description': 'ශල්‍යකර්මයට පෙර ඇගයීම්, උපවාසය අවශ්‍යතා, සහ මානසිකව හා ශාරීරිකව සූදානම් වන්නේ කෙසේද යන්න ගැන ඉගෙන ගන්න.',
    'whatToExpect.during.title': 'ශල්‍යකර්මය අතරතුර',
    'whatToExpect.during.description': 'විවිධ වර්ගයේ නිර්වින්දනයන්, ඒවා ක්‍රියාත්මක වන ආකාරය, විය හැකි සංකූලතා, සහ ඔබේ නිර්වින්දන කණ්ඩායමේ භූමිකාව ගැන සොයාගන්න.',
    'whatToExpect.after.title': 'ශල්‍යකර්මයෙන් පසු',
    'whatToExpect.after.description': 'ප්‍රකෘතිමත් වීමේ කාමරයේ සිදුවන දේ, පොදු අතුරු ආබාධ, වේදනා කළමනාකරණ උපාය මාර්ග සහ සාමාන්‍ය ක්‍රියාකාරකම් නැවත ආරම්භ කළ හැකි අවස්ථාව ගැන සොයා ගන්න.',
    'whatToExpect.learnMore': 'වැඩි විස්තර',
    
    // Before Surgery Page Translations - Sinhala
    'before.title': 'ශල්‍යකර්මයට පෙර',
    'before.intro': 'ඔබේ ක්‍රියාපටිපාටියට පෙර බලාපොරොත්තු විය හැකි දේ ගැන අවබෝධයක් ලබා ගැනීමෙන් කනස්සල්ල අඩු කිරීමට සහ හැකි උපරිම ප්‍රතිඵලයක් සහතික කිරීමට උපකාරී විය හැක.',
    'before.qa1.question': 'ශල්‍යකර්මයට පෙර ඇගයීම යනු කුමක්ද?',
    'before.qa1.answer1': 'නිර්වින්දනට පෙර අවදානම් හඳුනා ගැනීම සහ ඔබේ සෞඛ්‍යය වැඩිදියුණු කිරීම සඳහා ඔබේ වෛද්‍ය ඉතිහාසය, ශාරීරික පරීක්ෂණය, රුධිර පරීක්ෂණ, ECG සහ වෙනත් පරීක්ෂණ පිළිබඳ සවිස්තරාත්මක සමාලෝචනයකි.',
    'before.qa1.answer2': 'මෙම තක්සේරුව අතරතුර, ඔබේ නිර්වේදකයා:',
    'before.qa1.list1': 'ඔබේ වෛද්‍ය ඉතිහාසය සහ පෙර ශල්‍යකර්ම සමාලෝචනය කරනු ඇත',
    'before.qa1.list2': 'ඇලජි සහ වත්මන් ඖෂධ ගැන විමසනු ඇත',
    'before.qa1.list3': 'ඔබේ හෘදය සහ පෙනහළු කේන්ද්‍ර කර ගත් ශාරීරික පරීක්ෂණයක් සිදු කරනු ඇත',
    'before.qa1.list4': 'රුධිර පරීක්ෂණ සහ ECG ඇතුළු පරීක්ෂණ ප්‍රතිඵල ඇගයීම කරනු ඇත',
    'before.qa1.list5': 'නිර්වින්දන සැලැස්ම සාකච්ඡා කර ඔබේ ප්‍රශ්නවලට පිළිතුරු දෙනු ඇත',
    'before.qa2.question': 'නිරාහාරව සිටීම අවශ්‍ය වන්නේ ඇයි?',
    'before.qa2.answer1': 'නිර්වින්දන අතරතුර ඔබේ ආමාශයේ අඩංගු දේ ඔබේ පෙනහළු වලට ඇතුළු වීමේ අවදානම අඩු කිරීම සඳහා ශල්‍යකර්මයට පෙර උපවාසය අත්‍යවශ්‍ය වේ, එය aspiration නම් බරපතල සංකූලතාවයකි.',
    'before.qa2.guidelines': 'උපවාස මාර්ගෝපදේශ:',
    'before.qa2.list1': 'ඝන ආහාර සහ කිරි: ශල්‍යකර්මයට පැය 6කට පෙර නවත්වන්න',
    'before.qa2.list2': 'පැහැදිලි ද්‍රව (ජලය, කිරි නොමැති තේ): ශල්‍යකර්මයට පැය 2කට පෙර නවත්වන්න',
    'before.qa2.siptitle': 'සිප් ටිල් සෙන්ඩ් වැඩසටහන:',
    'before.qa2.siptext1': 'බොහෝ රෝහල් දැන් ශල්‍යකර්මයට පැය 2කට පෙර තෙක් පැහැදිලි ද්‍රව පානය කිරීමට රෝගීන් දිරිමත් කරයි. මෙය ජල විරහිත වීම වැළැක්වීමට උපකාරී වන අතර ඔබේ සුවය වැඩිදියුණු කළ හැක. "සිප් ටිල් සෙන්ඩ්" ක්‍රමලේඛය ගැන ඔබේ සෞඛ්‍ය සේවා සපයන්නාගෙන් විමසන්න.',
    'before.qa2.siptext2': 'සිප් ටිල් සෙන්ඩ් උපවාස තොරතුරු ගැන වැඩිදුර දැනගන්න',
    'before.qa3.question': 'මඟ හැරිය යුතු ඖෂධ මොනවාද?',
    'before.qa3.answer1': 'සමහර ඖෂධ නිර්දවින්දනයට බාධා කළ හැකි හෝ ශල්‍යකර්ම ලේ ගැලීමේ අවදානම වැඩි කළ හැකිය. ඔබ ගන්නා සියලුම ඖෂධ, ප්‍රතිඅපහරණ ඖෂධ සහ අතිරේක ඇතුළුව, ගැන සැම විටම ඔබේ නිර්වේදකයාට දැනුම් දෙන්න.',
    'before.qa3.subtitle': 'නැවැත්වීමට හෝ සකස් කිරීමට අවශ්‍ය විය හැකි ඖෂධ ඇතුළත්:',
    'before.qa3.list1': 'ලේ තුනී කරන: ඇස්පිරින්, ක්ලොපිඩොග්රෙල්, වෝෆරින්',
    'before.qa3.list2': ' වේදනා නාශක : අයිබූප්‍රෝෆන්, ඩයික්ලෝෆෙනැක්',
    'before.qa3.list3': 'පැළෑටි අතිරේක: ගින්කෝ, සුදුලූණු, මාළු තෙල්',
    'before.qa3.important': 'වැදගත්: ඔබේ වෛද්‍යවරයා හෝ නිර්වේදකයා හා සාකච්ඡා කිරීමෙන් තොරව කිසිවිටෙකත් බෙහෙත් දීම නතර නොකරන්න.',
    'before.qa4.question': 'මානසිකව හා ශාරීරිකව සූදානම් වන්නේ කෙසේද?',
    'before.qa4.physical': 'ශාරීරික සූදානම:',
    'before.qa4.plist1': 'ශල්‍යකර්මයට පෙර හොඳ රාත්‍රී නින්දක් ලබා ගන්න',
    'before.qa4.plist2': 'උපවාසය ආරම්භ වන තෙක් ජලය පානය කරන්න',
    'before.qa4.plist3': 'ඔබේ ශල්‍ය කණ්ඩායමගෙන් ලැබෙන විශේෂිත උපදෙස් අනුගමනය කරන්න',
    'before.qa4.plist4': 'ශල්‍යකර්මයට පැය 24කට පෙර සිට මධ්‍යසාර භාවිතයෙන් වළකින්න',
    'before.qa4.plist5': 'ඔබ දුම්පානය කරන්නේ නම්, ශල්‍යකර්මයට පෙර එය නැවැත්වීමට හෝ අඩු කිරීමට උත්සාහ කරන්න',
    'before.qa4.mental': 'මානසික සූදානම:',
    'before.qa4.mlist1': 'ඔබේ ශල්‍යකර්මයට පෙර තක්සේරුවේදී ඕනෑම ගැටළුවක් විසඳීමට ප්‍රශ්න අසන්න',
    'before.qa4.mlist2': 'ගැඹුරු හුස්ම ගැනීම හෝ භාවනාව වැනි සැහැල්ලු කිරීමේ ක්‍රම පුහුණු කරන්න',
    'before.qa4.mlist3': 'රෝහල් මාර්ගෝපදේශ තුළ සනසන අයිතම රැගෙන එන්න',
    'before.qa4.mlist4': 'නිකුත් කිරීමෙන් පසු පවුලේ අය හෝ මිතුරන්ගේ සහය සලසා ගන්න',
    'before.qa4.practical': 'ප්‍රායෝගික සූදානම:',
    'before.qa4.prlist1': 'රෝහලට යාමට සහ රෝහලෙන් ආපසු පැමිණීමට ප්‍රවාහනය සකස් කරන්න',
    'before.qa4.prlist2': 'ඔබේ ආපසු පැමිණීම සඳහා ඔබේ නිවස සූදානම් කරන්න (පහසු ආහාර, පහසු සුවය ලැබීමේ ප්‍රදේශය)',
    'before.qa4.prlist3': 'ඔබේ ඖෂධ, ඇලජි සහ පෙර නිර්වේදන අත්දැකීම් ලැයිස්තුවක් රැගෙන එන්න',
    'before.qa4.prlist4': 'ශල්‍යකර්මයට පෙර ආභරණ, පැළඳුම් සහ නිය තීන්ත ඉවත් කරන්න',
    'before.qa4.prlist5': 'ශල්‍යකර්මයට පෙර ස්නානය කිරීම පිළිබඳ විශේෂිත උපදෙස් අනුගමනය කරන්න',
    
    // During Surgery Translations - Sinhala
    'during.title': 'ශල්‍යකර්මය අතරතුර',
    'during.intro': 'ශල්‍යකර්මය අතරතුර සිදුවන දේ සහ නිර්වින්දනය ක්‍රියා කරන ආකාරය පිළිබඳ අවබෝධයක් ලබා ගැනීමෙන් ඔබට කනස්සල්ල අඩු කිරීමට සහ ඔබේ ක්‍රියාපටිපාටිය සඳහා සූදානම් වීමට උපකාරී විය හැක.',
    'during.qa1.question': 'නිර්වින්දනයේ වර්ග මොනවාද?',
    'during.qa1.general': 'සාමාන්‍ය නිර්වින්දනය  (GA):',
    'during.qa1.generalDesc': 'ඖෂධ මගින් ඇති කරන සිහිමූර්ජාව. ඔබේ ක්‍රියාපටිපාටිය අතරතුර ඔබ සම්පූර්ණයෙන්ම නොදැනුවත්ව සිටින අතර වේදනාවක් දැනීමට නොහැකි වනු ඇත.',
    'during.qa1.generalUse': 'සාමාන්‍යයෙන් භාවිතා කරන්නේ: ප්‍රධාන ශල්‍යකර්ම, ශරීර කුහර වල ක්‍රියාපටිපාටි, හෝ වෙනත් ආකාර සුදුසු නොවන විට.',
    'during.qa1.spinal': 'කශේරුකාවේ/එපිඩුරල් නිර්වින්දනය :',
    'during.qa1.spinalDesc': 'ඉඟට පහළ ස්නායු සම්ප්‍රේෂණය අවහිර කිරීම සඳහා සබරැචයිඩ් අවකාශයට (කශේරුකාව) හෝ එපිඩුරල් අවකාශයට පෙදෙසීය නිර්වේදකය එන්නත් කිරීම.',
    'during.qa1.spinalUse': 'සාමාන්‍යයෙන් භාවිතා කරන්නේ: පහළ ශරීරයේ ක්‍රියාපටිපාටි, සීසර් සැත්කම්, ඉඟටිය/දණහිස ශල්‍යකර්ම සඳහා.',
    'during.qa1.nerve': 'පරිධීය ස්නායු අවහිර කිරීම:',
    'during.qa1.nerveDesc': 'ශරීරයේ විශේෂිත ප්‍රදේශයක් අමාරුවෙන් තොරව සිටීම සඳහා නිශ්චිත ස්නායු අසලට පෙදෙසීය නිර්වේදකය එන්නත් කිරීම.',
    'during.qa1.nerveUse': 'සාමාන්‍යයෙන් භාවිතා කරන්නේ: අත්, උරහිස, හෝ කකුල් ශල්‍යකර්ම සඳහා, ඉලක්කගත වේදනා සහනය ලබා දෙමින්.',
    'during.qa1.sedation': 'ප්‍රබුද්ධ සන්සුන්තාව (අධීක්ෂිත නිර්වේදන සත්කාරය):',
    'during.qa1.sedationDesc': 'ප්‍රබුද්ධ බව පවත්වා ගනිමින් ඔබට විශ්‍රාම ගැනීමට සහ වේදනාව අඩු කිරීමට උපකාරී වන ඖෂධ.',
    'during.qa1.sedationUse': 'සාමාන්‍යයෙන් භාවිතා කරන්නේ: සුළු ක්‍රියාපටිපාටි, එන්ඩොස්කොපි, දන්ත කටයුතු සඳහා.',
    
    'during.qa2.question': 'නිර්වින්දනයේ එක් එක් වර්ගය ක්‍රියා කරන්නේ කෙසේද?',
    'during.qa2.general': 'සාමාන්‍ය නිර්වේදන යාන්ත්‍රණය:',
    'during.qa2.generalDesc': 'සාමාන්‍ය නිර්වින්දන ක්‍රියා කරන්නේ පහත ඖෂධවල සංයෝගයක් හරහාය:',
    'during.qa2.generalList1': 'සිහිමූර්ජාව ඇති කරයි (ප්‍රොපොෆොල්, තයෝපෙන්ටල්)',
    'during.qa2.generalList2': 'සිහිමූර්ජාව පවත්වාගෙන යාම (සෙවෝෆ්ලුරේන්, ඩෙස්ෆ්ලුරේන් වායු)',
    'during.qa2.generalList3': 'මාංශපේශි ලිහිල් කරයි (රොකුරෝනියම්, සක්සිනයිල්කොලයින්)',
    'during.qa2.generalList4': 'වේදනාව අවහිර කරයි (ෆෙන්ටනිල්, මෝෆින්)',
    'during.qa2.generalEnd': 'මෙම ඖෂධ ඔබේ මධ්‍යම ස්නායු පද්ධතිය පාලනය කළ හැකි ආකාරයෙන් අඩපණ කරයි, පිළිවර්ත සිහිමූර්ජා තත්ත්වයක් ඇති කිරීම සඳහා විවිධ මොළයේ ග්‍රාහක වලට බලපෑම් කරමින්.',
    'during.qa2.spinal': 'කශේරුකාවේ/එපිඩුරල් යාන්ත්‍රණය:',
    'during.qa2.spinalDesc': 'කශේරුකාවේ කේතය අසල පෙදෙසීය නිර්වේදක (බුපිවකේන් වැනි) එන්නත් කරනු ලැබේ:',
    'during.qa2.spinalList1': 'කශේරුකාව: සෘජුවම කශේරුකාවේ කේතය වටා ඇති සෙරීබ්‍රොස්පයිනල් තරලය තුළට',
    'during.qa2.spinalList2': 'එපිඩුරල්: කශේරුකාවේ කේතය ආවරණ වලින් බාහිර අවකාශයට',
    'during.qa2.spinalEnd': 'මෙම ඖෂධය ස්නායු පටල වල සෝඩියම් නාලිකා අවහිර කරයි, ස්නායු ආවේග කශේරුකාවේ කේතය ඔස්සේ මොළයට ගමන් කිරීම වළක්වයි.',
    'during.qa2.nerve': 'පරිධීය ස්නායු අවහිරතා යාන්ත්‍රණය:',
    'during.qa2.nerveDesc': 'අල්ට්‍රාසවුන්ඩ් මඟපෙන්වීම භාවිතා කරමින්, නිර්වේදකයින් විශේෂිත ස්නායු බඳුන් වටා පෙදෙසීය නිර්වේදක එන්නත් කරති. ඒ ඖෂධය ප්‍රබුද්ධ බවට බලපෑමක් නොකර එම නිශ්චිත ප්‍රදේශයේ ස්නායු සම්ප්‍රේෂණය තාවකාලිකව අවහිර කරයි.',
    'during.qa2.sedation': 'සන්සුන් කිරීමේ යාන්ත්‍රණය:',
    'during.qa2.sedationDesc': 'මිඩසොලම් (බෙන්සොඩයසෙපින්) සහ ෆෙන්ටනිල් (ඕපියොයිඩ්) වැනි ඖෂධ වල සාවධානව අනුමත කරන ලද මාත්‍රා පහත තත්ත්වයක් ඇති කරයි:',
    'during.qa2.sedationList1': 'කනස්සල්ල අඩු කිරීම',
    'during.qa2.sedationList2': 'වේදනා සංවේදනය අඩු කිරීම',
    'during.qa2.sedationList3': 'අමතකවීම (ක්‍රියාපටිපාටිය පිළිබඳ මතකය අඩුවීම)',
    'during.qa2.sedationList4': 'ප්‍රබුද්ධ බව සහ ආරක්ෂක ප්‍රතික්ෂේප පවත්වාගෙන යාම',
    
    'during.qa3.question': 'අවදානම් සහ සංකූලතා, වැළැක්වීම සහ කළමනාකරණය',
    'during.qa3.minor': 'සාමාන්‍ය සුළු බලපෑම්:',
    'during.qa3.minorList1': 'සීතල වීම (20%) - උණුසුම් දෙන පොරවන මගින් වළක්වා ඇත',
    'during.qa3.minorList2': 'ශල්‍යකර්මයෙන් පසු ඔක්කාරය සහ වමනය (25%) - ඖෂධ මගින් පාලනය කරයි',
    'during.qa3.minorList3': 'උගුරේ අමාරුව (15%)',
    'during.qa3.minorList4': 'හිසරදය (10%) - ජලය පිනුම සහ මෘදු වේදනා නාශක මගින් ප්‍රතිකාර කරයි',
    'during.qa3.regional': 'කලාපීය/කශේරුකාවේ නිර්වේදන අවදානම්:',
    'during.qa3.regionalList1': 'හිසරදය (1-2%) - ජලය, කැෆීන්, හෝ එපිඩුරල් රුධිර පැච් මගින් කළමනාකරණය කරනු ලැබේ',
    'during.qa3.regionalList2': 'තාවකාලික ස්නායුක රෝග ලක්ෂණ (0.5%) - සාමාන්‍යයෙන් කාලය සමඟ යථා තත්ත්වයට පත් වේ',
    'during.qa3.regionalList3': 'මූත්‍රා අඩස්සිය - අවශ්‍ය නම් තාවකාලික කැතෙටරයක් භාවිතා කරයි',
    'during.qa3.serious': 'බරපතල නමුත් කලාතුරකින් සිදුවන සංකූලතා:',
    'during.qa3.seriousList1': 'ඇනෆිලැක්සිස් (10,000 න් 1) - අධීක්ෂණය මගින් හඳුනාගෙන එපිනෆ්‍රින් සමඟ ප්‍රතිකාර කරනු ලැබේ',
    'during.qa3.seriousList2': 'වයසන අධි උණුසුම (< 50,000 න් 1) - ඩැන්ට්‍රොලීන් සමඟ ප්‍රතිකාර කරනු ලබන ජාන තත්ත්වය',
    'during.qa3.seriousList3': 'ස්ථිර ස්නායු හානි (< 100,000 න් 1) - සැලකිලිමත් පිහිටුවීම සහ තාක්ෂණය මගින් වළක්වා ඇත',
    'during.qa3.seriousList4': 'සාමාන්‍ය නිර්වේදනය අතරතුර දැනුවත් වීම (< 1,000 න් 1) - BIS තාක්ෂණය භාවිතා කරමින් අධීක්ෂණය කරනු ලබයි',
    'during.qa3.airway': 'වායු මාර්ග සංකූලතා:',
    'during.qa3.airwayList1': 'අපහසු නාලය දැමීම (1-3%)',
    'during.qa3.airwayList2': 'අවශෝෂණය (< 1%) ආමාශ තරලය පිට උගුරේ යාම- නිරාහාරව සිටීම මගින් වලක්වා ගත හැක',
    'during.qa3.airwayList3': 'දන්ත හානි (< 0.5%) - සැලකිලිමත් තාක්ෂණය මගින් අවම කරනු ලබයි',
    'during.qa3.remember': 'මතක තබා ගන්න: ඔබේ නිරවින්දන වෛද්‍යවරයා මෙම සංකූලතා වළක්වා ගැනීමට, අනාවරණය කර ගැනීමට සහ කළමනාකරණය කිරීමට ඉතා උසස් පුහුණුවක් ලබා ඇත. නිර්වින්දනයන් බහුතරයක් කිසිදු බරපතල ගැටළුවකින් තොරව පරිපාලනය කෙරේ.',
    
    'during.qa4.question': 'අධීක්ෂණය සහ ආරක්ෂක පියවර',
    'during.qa4.standard': 'සම්මත මොනිටර (ASA මාර්ගෝපදේශ):',
    'during.qa4.standardList1': 'ECG - හෘද වේගය සහ රිද්මය අධීක්ෂණය කරයි',
    'during.qa4.standardList2': 'NIBP - ආක්‍රමණශීලී නොවන රුධිර පීඩනය, සාමාන්‍යයෙන් මිනිත්තු 3-5කට වරක් මනිනු ලබයි',
    'during.qa4.standardList3': 'SpO₂ - නබ්‍ස් ඔක්සිමීටරය හරහා ඔක්සිජන් සම්පෘක්තතාව',
    'during.qa4.standardList4': 'ETCO₂ - නිසි ලෙස හුස්ම ගැනීම තහවුරු කිරීම සඳහා අවසාන කාබන් ඩයොක්සයිඩ්',
    'during.qa4.standardList5': 'උෂ්ණත්වය - හයිපොතර්මියාව හෝ හයිපර්තර්මියාව අනාවරණය කර ගැනීමට සහ වැළැක්වීමට',
    'during.qa4.advanced': 
    'during.qa4.advancedList1': 
    'during.qa4.advancedList2': 
    'during.qa4.advancedList3': 
    'during.qa4.advancedList4':
    'during.qa4.targets': 'සාමාන්‍ය ඉලක්ක අගයන්:',
    'during.qa4.targetsList1': 'SpO₂: > 95%',
    'during.qa4.targetsList2': 'ETCO₂: 35-45 mmHg',
    'during.qa4.targetsList3': 'MAP (මාධ්‍ය ධමනි පීඩනය): 65-90 mmHg',
    'during.qa4.targetsList4': 'උෂ්ණත්වය: 36-37°C (97-99°F)',
    'during.qa4.safety': 'ආරක්ෂක ක්‍රමලේඛ:',
    'during.qa4.safetyList1': 'සම්මත පිරික්සුම් ලැයිස්තු භාවිතා කරමින් නිර්වේදනයට පෙර උපකරණ පරීක්ෂා කිරීම',
    'during.qa4.safetyList2': 'කැපීමට පෙර WHO ශල්‍යකර්ම ආරක්ෂණ පරීක්ෂා ලැයිස්තුව',
    'during.qa4.safetyList3': 'හදිසි ඖෂධ සහ උපකරණ වලට වහාම ප්‍රවේශය',
    'during.qa4.safetyList4': 'ප්‍රධාන සංඥා වෙනස්කම් සඳහා අඛණ්ඩ දෘශ්‍ය සහ ශ්‍රවණ ඇඟවීම්',
    'during.qa4.safetyList5': 'නිවැරදි ශ්වසන නළ පිහිටීම තහවුරු කිරීම සඳහා කැප්නොග්‍රැෆි',
    'during.qa4.modern': 'නවීන නිර්වේදන අධීක්ෂණය ආරක්ෂාව සැලකිය යුතු ලෙස වැඩි දියුණු කර ඇත. ඔබේ ප්‍රධාන සංඥා ඔබේ ක්‍රියාපටිපාටිය පුරාවටම ඔබේ නිර්වේදන කණ්ඩායම විසින් අඛණ්ඩව පෙන්වා සහ අධීක්ෂණය කරනු ලැබේ.',
    
    'during.qa5.question': 'ශල්‍යකර්මය අතරතුර නිර්වේදකයාගේ කාර්යභාරය',
    'during.qa5.intro': 'ඔබේ නිර්වේදකයා යනු ඔබේ ආරක්ෂාව හා සුවපහසුව කෙරෙහි විශේෂයෙන් අවධානය යොමු කරමින් ඔබේ සමස්ත ශල්‍යකර්මය පුරාවටම ඔබ සමඟ රැඳී සිටින විශේෂ පුහුණුවක් ලත් වෛද්‍යවරයෙකි.',
    'during.qa5.responsibilities': 'නිර්වේදකයාගේ වගකීම් වලට ඇතුළත්:',
    'during.qa5.respList1': 'ප්‍රධාන සංඥා, නිර්වේදනයේ ගැඹුර, වේදනා පාලනය සහ ද්‍රව තත්ත්වය පිළිබඳ අඛණ්ඩ තක්සේරුව',
    'during.qa5.respList2': 'ඔබේ අවශ්‍යතා සහ ශල්‍ය අවශ්‍යතා මත පදනම්ව ශල්‍යකර්මය පුරා ගතික ඖෂධ ගැලපීම්',
    'during.qa5.respList3': 'රුධිර පීඩන වෙනස්කම්, රිද්මතා, හෝ ලේ ගැලීම වැනි අනපේක්ෂිත සිදුවීම් කළමනාකරණය කිරීම',
    'during.qa5.respList4': 'කාලය, පිහිටීම සහ විශේෂ අවශ්‍යතා ගැන ශල්‍ය වෛද්‍යවරුන් සමඟ සම්බන්ධීකරණය',
    'during.qa5.respList5': 'රෝගියා වෙනුවෙන් පෙනී සිටීම, ඔබේ ආරක්ෂාව, අභිමානය සහ සුවපහසුව සෑම විටම සහතික කිරීම',
    'during.qa5.respList6': 'රුධිර සංක්‍රාමණ, ද්‍රව කළමනාකරණය සහ වේදනා පාලනය පිළිබඳ වෛද්‍ය තීරණ ගැනීම',
    'during.qa5.team': 'කණ්ඩායම් ප්‍රවේශය:',
    'during.qa5.teamDesc': 'ඔබේ නිර්වේදකයා බොහෝ විට පහත සඳහන් කණ්ඩායමක් සමඟ වැඩ කරයි:',
    'during.qa5.teamList1': 'නිර්වේදක සහායකයින් හෝ තාක්ෂණිකයින්',
    'during.qa5.teamList2': 'නිර්වේදක හෙදියන් (සමහර රටවල)',
    'during.qa5.teamList3': 'අධීක්ෂණය යටතේ නිර්වේදක පුහුණුවන්නන්',
    'during.qa5.think': 'ශල්‍යකර්මය අතරතුර ඔබේ නිර්වේදකයා ඔබේ පෞද්ගලික "ජීවන කාර්යයන් කළමනාකරු" ලෙස සිතන්න, ඔබ සිහිමූර්ජා වී හෝ සන්සුන් කර ඇති අතරතුරදී ඔබේ ශරීරයේ පද්ධති ස්ථාවරව පවතින බව සහතික කිරීම සඳහා නිරන්තරයෙන් නිරීක්ෂණය කරමින් සහ ගලපමින්.',
    
    // After Surgery Translations - Sinhala
    'after.title': 'ශල්‍යකර්මයෙන් පසු',
    'after.intro': 'ඔබේ ක්‍රියාපටිපාටියෙන් පසු බලාපොරොත්තු විය හැකි දේ ගැන අවබෝධයක් ලබා ගැනීමෙන් ඔබට ප්‍රකෘතිමත් වීම සඳහා සූදානම් වීමට සහ සාමාන්‍ය සහ අසාමාන්‍ය රෝග ලක්ෂණ හඳුනා ගැනීමට උපකාරී විය හැක.',
    'after.qa1.question': 'ප්‍රකෘතිමත් වීමේ කාමරයේ සිදු වන්නේ කුමක්ද?',
    'after.qa1.intro': 'ඔබේ ශල්‍යකර්මයෙන් පසු, ඔබව ප්‍රකෘතිමත් වීමේ කාමරය ලෙසද හැඳින්වෙන පසු-නිර්වේදන සත්කාර ඒකකයට (PACU) මාරු කරනු ලැබේ. මෙය ඔබ නිර්වින්දනයෙන් ඉවත් වන විට සමීපව අධීක්ෂණය කරනු ලබන විශේෂිත ප්‍රදේශයකි.',
    'after.qa1.expect': 'PACU හිදී, ඔබට බලාපොරොත්තු විය හැක්කේ:',
    'after.qa1.monitoring': 'අඛණ්ඩ අධීක්ෂණය',
    'after.qa1.monitoringDesc': 'ඔබේ ප්‍රධාන සංඥා (රුධිර පීඩනය, හෘද වේගය, ඔක්සිජන් මට්ටම)',
    'after.qa1.nursing': 'එක් අයෙකු සඳහා එක් හෙද සත්කාරය',
    'after.qa1.nursingDesc': 'ඔබ සම්පූර්ණයෙන් අවදි වන තුරු සහ ස්ථාවර වන තුරු',
    'after.qa1.assessments': 'නිතිපතා ඇගයීම්',
    'after.qa1.assessmentsDesc': 'ඔබේ වේදනා මට්ටම් සහ අවශ්‍ය පරිදි වේදනා ඖෂධ පරිපාලනය',
    'after.qa1.oxygen': 'ඔක්සිජන් චිකිත්සාව',
    'after.qa1.oxygenDesc': 'අවශ්‍ය නම් මුහුණු ආවරණයක් හෝ නාසාග්‍ර හරහා',
    'after.qa1.warming': 'උණුසුම් කම්බල',
    'after.qa1.warmingDesc': 'ඔබ සීතල හෝ සීතල වීමක් නම්',
    'after.qa1.iv': 'IV ද්‍රව',
    'after.qa1.ivDesc': 'ඔබට පානය කිරීමට හැකි වන තුරු',
    'after.qa1.howLong': 'මම ප්‍රකෘතිමත් වීමේ කාමරයේ කොපමණ කාලයක් රැඳී සිටින්නේද?',
    'after.qa1.timeFrame': 'බොහෝ රෝගීන් PACU හි මිනිත්තු 30 සිට පැය 2 දක්වා රැඳී සිටිනු ඇත, පහත කරුණු මත රඳා පවතී:',
    'after.qa1.timeList1': 'ඔබට ලැබුණු ශල්‍යකර්මයේ සහ නිර්වින්දනයේ වර්ගය',
    'after.qa1.timeList2': 'ඔබ කෙතරම් ඉක්මනින් අවදි වන්නේද සහ ස්ථාවර වන්නේද',
    'after.qa1.timeList3': 'ඔබේ වේදනාව සහ ඕනෑම ඔක්කාරයක් කොපමණ හොඳින් පාලනය කරන්නේද',
    'after.qa1.timeList4': 'ශල්‍යකර්මය අතරතුර සංකූලතා තිබුණේද',
    'after.qa1.transfer': 'ප්‍රකෘතිමත් වීමේ කණ්ඩායම ඔබේ තත්ත්වය ගැන සෑහීමකට පත් වූ පසු ඔබව වාට්ටුවකට මාරු කරනු ලබන්නේ හෝ නිවසට මුදා හරිනු ලබන්නේය.',
    
    'after.qa2.question': 'සාමාන්‍ය ශල්‍යකර්මයෙන් පසු අතුරු ආබාධ සහ වේදනා පාලනය',
    'after.qa2.sideEffects': 'සාමාන්‍ය අතුරු ආබාධ:',
    'after.qa2.throat': 'උගුරේ අමාරුව',
    'after.qa2.throatDesc': '- හුස්ම නළයෙන්; සාමාන්‍යයෙන් පැය 24-48 තුළ සුව වේ',
    'after.qa2.nausea': 'ඔක්කාරය සහ වමනය',
    'after.qa2.nauseaDesc': '- ප්‍රති-අසනීප ඖෂධ සමඟ ප්‍රතිකාර කළ හැක',
    'after.qa2.dizziness': 'හිසර කැරකැවීම',
    'after.qa2.dizzinessDesc': '- බොහෝ විට මෘදු චලනය සහ ජලය පානය කිරීමෙන් වැඩි දියුණු වේ',
    'after.qa2.drowsiness': 'නිදිමත බව',
    'after.qa2.drowsinessDesc': '- නිර්වින්දන පහව යන විට ක්‍රමයෙන් වැඩි දියුණු වේ',
    'after.qa2.shivering': 'සීතල වීම',
    'after.qa2.shiveringDesc': '- සාමාන්‍යයෙන් තාවකාලිකයි; උණුසුම් කම්බල මගින් ප්‍රතිකාර කරනු ලැබේ',
    'after.qa2.confusion': 'වික්ෂිප්තභාවය',
    'after.qa2.confusionDesc': '- වයස්ගත වැඩිහිටියන් තුළ වඩාත් පොදුය; සාමාන්‍යයෙන් තාවකාලිකයි',
    'after.qa2.painManagement': 'වේදනා කළමනාකරණ විකල්ප:',
    'after.qa2.ivPain': 'IV වේදනා ඖෂධ',
    'after.qa2.ivPainDesc': '- වහාම සහනය සඳහා බොහෝ විට මෝෆින් වැනි ඕපියොයිඩ්',
    'after.qa2.pca': 'රෝගියා-පාලිත වේදනා නාශක (PCA)',
    'after.qa2.pcaDesc': '- බොත්තමක් එබීමෙන් ඔබට වේදනා ඖෂධ වල කුඩා මාත්‍රා ස්වයං පරිපාලනය කිරීමට ඉඩ සලසයි',
    'after.qa2.oral': 'මුඛ වේදනා ඖෂධ',
    'after.qa2.oralDesc': '- ඔබට ද්‍රව පානය කළ හැකි වූ පසු පෙති හෝ ද්‍රව',
    'after.qa2.blocks': 'කලාපීය අවහිරතා',
    'after.qa2.blocksDesc': '- ශල්‍යකර්මයෙන් පසු පැය ගණනක් වේදනා සහනය ලබා දීමට ඉඩ ඇත',
    'after.qa2.local': 'පෙදෙසීය නිර්වේදක පුරණය',
    'after.qa2.localDesc': '- ශල්‍ය ස්ථානය වටා එන්නත් කරනු ලැබේ',
    'after.qa2.nonMed': 'ඖෂධ නොවන තාක්ෂණ',
    'after.qa2.nonMedDesc': '- අයිස් පැක්, පිහිටුවීම, සැහැල්ලු කිරීමේ තාක්ෂණ',
    'after.qa2.tips': 'වැදගත් වේදනා කළමනාකරණ ඉඟි:',
    'after.qa2.tipsList1': 'වේදනා සහනය ඉල්ලීමට පෙර වේදනාව දරුණු වන තෙක් රැඳී සිටීමෙන් වළකින්න',
    'after.qa2.tipsList2': 'සෞඛ්‍ය කාර්ය මණ්ඩලය විසින් විමසන විට ඔබේ වේදනාව 0-10 පරිමාණයක සිට අගයන්න',
    'after.qa2.tipsList3': 'වේදනා ඖෂධ ක්‍රියා නොකරන්නේ නම් හෝ ඉක්මනින් පහව යන්නේ නම් ඔබේ හෙදියන්ට පවසන්න',
    'after.qa2.tipsList4': 'වේදනා ඖෂධ වලින් අසාමාන්‍ය රෝග ලක්ෂණ හෝ අතුරු ආබාධ වාර්තා කරන්න',
    
    'after.qa3.question': 'මට ආහාර සහ බීම ගත හැක්කේ කවදාද?',
    'after.qa3.intro': 'ශල්‍යකර්මයෙන් පසු ආහාර ගැනීම සහ පානය කිරීම නැවත ආරම්භ කිරීම ශල්‍යකර්මයේ වර්ගය, භාවිතා කරන ලද නිර්වින්දනය, සහ ඔබේ පුද්ගලික ප්‍රකෘතිමත් වීම ඇතුළු සාධක කිහිපයක් මත රඳා පවතී.',
    'after.qa3.guidelines': 'සාමාන්‍ය මාර්ගෝපදේශ:',
    'after.qa3.fluids': 'පැහැදිලි ද්‍රව',
    'after.qa3.fluidsDesc': '(ජලය, ඇපල් යුෂ) - බොහෝ විට නිර්වින්දනයෙන් සම්පූර්ණයෙන් අවදි වීමෙන් පසු පැය 2-4ක් ඇතුළත, ඔබට ආරක්ෂිතව ගිලින්නට හැකි වූ පසු අවසර දී ඇත',
    'after.qa3.light': 'සැහැල්ලු ආහාර',
    'after.qa3.lightDesc': '(ක්‍රැකර්ස්, පාන්, සූප්) - සාමාන්‍යයෙන් ද්‍රව හොඳින් ඉවසා සිටින විට, බොහෝ විට ශල්‍යකර්මයෙන් පසු පැය 4-6 අවසර දී ඇත',
    'after.qa3.regular': 'සාමාන්‍ය ආහාර වේල',
    'after.qa3.regularDesc': '- සාමාන්‍යයෙන් ඉවසා සිටින පරිදි ක්‍රමයෙන් නැවත ආරම්භ කරනු ලැබේ, බොහෝ විට සුළු ශල්‍යකර්ම සඳහා පසු දින',
    'after.qa3.considerations': 'විශේෂ සලකා බැලීම්:',
    'after.qa3.abdominal': 'බඩේ ශල්‍යකර්මය',
    'after.qa3.abdominalDesc': '- අන්ත්‍ර හඬ නැවත පැමිණෙන තුරු සහ ගෑස් හෝ මළ පහ වීම සිදු වන තුරු රැඳී සිටීමට අවශ්‍ය විය හැක',
    'after.qa3.throat': 'උගුර හෝ මුඛයේ ශල්‍යකර්මය',
    'after.qa3.throatDesc': '- විශේෂ ආහාර සීමා අවශ්‍ය විය හැක',
    'after.qa3.nausea': 'ඔක්කාරය හෝ වමනය',
    'after.qa3.nauseaDesc': '- රෝග ලක්ෂණ වැඩි දියුණු වන තුරු ආහාර ගැනීමට ආපසු යාම ප්‍රමාද විය හැක',
    'after.qa3.medications': 'සමහර ඖෂධ',
    'after.qa3.medicationsDesc': '- ආහාර සමඟ ගත යුතු විය හැක, ඔබට ඒවා නැවත ආරම්භ කළ හැකි අවස්ථාවට බලපායි',
    'after.qa3.always': 'ඔබේ ක්‍රියාපටිපාටියෙන් පසු ආහාර ගැනීම සහ පානය කිරීම පිළිබඳව ඔබේ සෞඛ්‍ය සේවා සපයන්නාගේ නිශ්චිත උපදෙස් සැම විටම අනුගමනය කරන්න. සෙමින් ආරම්භ කර ඉවසා සිටින පරිදි ක්‍රමයෙන් වැඩි කරන්න.',
    
    'after.qa4.question': 'නිකුත් කිරීමේ උපදෙස් සහ පසුවිපරම්',
    'after.qa4.instructions': 'සාමාන්‍ය නිකුත් කිරීමේ උපදෙස්:',
    'after.qa4.activity': 'ක්‍රියාකාරකම් සීමා කිරීම්',
    'after.qa4.activityDesc': '- ඔබට සාමාන්‍ය ක්‍රියාකාරකම්, රිය පැදවීම, වැඩ සහ ව්‍යායාම වලට ආපසු යා හැක්කේ කවදාද',
    'after.qa4.wound': 'තුවාල සත්කාරය',
    'after.qa4.woundDesc': '- ශල්‍ය ස්ථානය පිරිසිදු කර ඇඳුම් කරන ආකාරය',
    'after.qa4.medication': 'ඖෂධ උපදෙස්',
    'after.qa4.medicationDesc': '- නියම කර ඇති ඖෂධ ගන්නේ කවදාද සහ කෙසේද',
    'after.qa4.infection': 'ආසාදන ලක්ෂණ',
    'after.qa4.infectionDesc': '- අධීක්ෂණය කළ යුතු දේ (වැඩි වන වේදනාව, රතු වීම, ඉදිමීම, විසර්ජනය, උණ)',
    'after.qa4.diet': 'ආහාර මාර්ගෝපදේශ',
    'after.qa4.dietDesc': '- ප්‍රකෘතිමත් වීම අතරතුර ඕනෑම විශේෂ ආහාර අවශ්‍යතා',
    'after.qa4.showering': 'ස්නානය/නාන',
    'after.qa4.showeringDesc': '- ශල්‍ය ප්‍රදේශය තෙත් කිරීම ආරක්ෂිත වන්නේ කවදාද',
    'after.qa4.contact': 'සම්බන්ධ කර ගත හැකි තොරතුරු',
    'after.qa4.contactDesc': '- ඔබට ප්‍රශ්න හෝ ගැටලු ඇත්නම් සම්බන්ධ කර ගත යුත්තේ කාවද',
    'after.qa4.appointments': 'පසු විපරම් හමුවීම්:',
    'after.qa4.appointmentsDesc': 'ඔබේ නිකුත් කිරීමේ උපදෙස් වල පසු විපරම් සංචාර පිළිබඳ විස්තර ඇතුළත් වනු ඇත. සාමාන්‍යයෙන්, ඔබට ඇත්තේ:',
    'after.qa4.appointmentsList1': 'ඔබේ සුව වීම පරීක්ෂා කිරීමට ඔබේ ශල්‍ය වෛද්‍යවරයා සමඟ හමුවීමක්',
    'after.qa4.appointmentsList2': 'ඕනෑම මැහුම් හෝ ස්ටේපල් ඉවත් කිරීම සඳහා උපදෙස්',
    'after.qa4.appointmentsList3': 'අවශ්‍ය ඕනෑම ශාරීරික චිකිත්සාව පිළිබඳ තොරතුරු',
    'after.qa4.keepAppts': 'ඔබ හොඳින් හැඟී සිටියත්, සියලුම පසු විපරම් හමුවීම් පවත්වා ගැනීමට වග බලා ගන්න.',
    'after.qa4.seekHelp': 'වහාම වෛද්‍ය ප්‍රතිකාර ලබා ගත යුතු අවස්ථා:',
    'after.qa4.seekList1': 'හුස්ම ගැනීමේ අපහසුතාවය හෝ හුස්ම හිරවීම',
    'after.qa4.seekList2': 'පපුවේ වේදනාව හෝ අක්‍රමවත් හෘද වේගය',
    'after.qa4.seekList3': 'නියම කර ඇති ඖෂධ මගින් පාලනය නොකරන දරුණු වේදනාව',
    'after.qa4.seekList4': 'අධික ලේ ගැලීම හෝ තුවාල විසර්ජනය',
    'after.qa4.seekList5': 'ආසාදන ලක්ෂණ (උණ 38°C/100.4°F ඉහළ, වැඩිවන රතු වීම හෝ උණුසුම)',
    'after.qa4.seekList6': 'ශල්‍යකර්මයෙන් පසු පැය 8-10ක් ඇතුළත මූත්‍ර කිරීමට නොහැකි වීම',
    'after.qa4.seekList7': 'දිගටම පවතින ඔක්කාරය සහ වමනය',
    'after.qa4.seekList8': 'කලවා වේදනාව, ඉදිමීම, හෝ රතු වීම (විය හැකි රුධිර කැටිගැසීම)',
    'after.qa4.pathway': 'ප්‍රකෘතිමත් වීමේ මාර්ගය:',
    'after.qa4.pathwayDesc': 'ඔබේ ප්‍රකෘතිමත් වීම සාමාන්‍ය රටාවක් අනුගමනය කරනු ඇත, නමුත් සෑම කෙනෙකුම ඔවුන්ගේම වේගයෙන් සුව වේ. ඔබේ ශරීරය සමඟ ඉවසිලිවන්ත වන්න සහ හොඳම ප්‍රතිඵලය සහතික කිරීම සඳහා සියලුම වෛද්‍ය උපදෙස් අනුගමනය කරන්න.',
    'after.qa4.keepInstructions': 'ඔබේ නිකුත් කිරීමේ උපදෙස් පහසුවෙන් ප්‍රවේශ විය හැකි ස්ථානයක තබා ගෙන පසු විපරම් හමුවීම් වලට ඔබ සමඟ රැගෙන යන්න.'
  },
  ta: {
    'site.title': 'மயக்க மருந்தியல் தகவல் மையம்',
    'nav.home': 'முகப்பு',
    'nav.before': 'அறுவைச் சிகிச்சைக்கு முன்',
    'nav.during': 'அறுவைச் சிகிச்சையின் போது',
    'nav.after': 'அறுவைச் சிகிச்சைக்குப் பின்',
    'nav.resources': 'வளங்கள்',
    'hero.title': 'மயக்க மருந்தியல் பற்றிய முழுமையான புரிதல்: உங்கள் அறுவை சிகிச்சைக்கு முன், அதன் போது, மற்றும் பின் நீங்கள் அறிய வேண்டியவை ',
    'hero.subtitle': 'பாதுகாப்பான, வசதியான அறுவைச் சிகிச்சை அனுபவத்திற்கான உங்கள் வழிகாட்டி',
    'hero.intro': "மயக்க மருந்தியல் (Anaesthesia) என்பது ஒரு மருத்துவத் துறையாகும். இது நீங்கள் வலியில்லாமல், பாதுகாப்பாக அறுவை சிகிச்சை செய்துகொள்ள உதவுகிறது. இன்றைய நவீன மயக்க மருந்து நுட்பங்கள், உங்கள் சௌகரியம் மற்றும் நலனில் அர்ப்பணிப்புடன் செயற்படும் மயக்க மருந்து நிபுணரால் (Anaesthetist) கவனமாகக் கண்காணிக்கப்படுகின்றன..",
    'cta.before': 'அறுவைச் சிகிச்சைக்கு முன்',
    'cta.during': 'அறுவைச் சிகிச்சையின் போது',
    'cta.after': 'அறுவைச் சிகிச்சைக்குப் பின்',
    'about.title': 'எம்மைப் பற்றி',
    'about.whoTitle': 'நாங்கள் யார்',
    'about.who': 'இலங்கையின் மயக்க மருந்து மற்றும் அதிதீவிர சிகிச்சைப் பிரிவு (Anaesthesia and Critical Care) குழுக்களின் கூட்டு முயற்சி இதுவாகும். நோயாளிகளுக்கு நம்பகமான தகவல்களைப் பகிர்வதே எங்கள் நோக்கம்..',
    'about.whyTitle': 'இந்த வளம் ஏன் உருவாக்கப்பட்டது',
    'about.why': 'நோயாளிகளின் பொதுவான கேள்விகளுக்குப் பதிலளிக்கவும், அவர்களின் பதட்டத்தைக் குறைக்கவும், மற்றும் அறுவை சிகிச்சை குறித்த தெளிவான புரிதலை ஊக்குவிக்கவும் இது உருவாக்கப்பட்டுள்ளது.',
    
    // What to Expect Section on Home Page - Tamil
    'whatToExpect.title': 'என்ன எதிர்பார்க்கலாம்?',
    'whatToExpect.before.title': 'அறுவை சிகிச்சைக்கு முன்',
    'whatToExpect.before.description': 'அறுவை சிகிச்சைக்கு முந்தைய மதிப்பீடுகள், உணவுத் தேவைகள், மற்றும் உங்கள் அறுவை சிகிச்சைக்கு மன ரீதியாகவும் உடல் ரீதியாகவும் எப்படித் தயாராவது என்பதைப் பற்றி அறிந்து கொள்ளுங்கள்.',
    'whatToExpect.during.title': 'அறுவை சிகிச்சையின்போது',
    'whatToExpect.during.description': 'மயக்க மருந்தின் பல்வேறு வகைகள், அவை எவ்வாறு செயல்படுகின்றன, ஏற்படக்கூடிய சிக்கல்கள் மற்றும் உங்கள் மயக்க மருந்து குழுவின் பங்கு பற்றி கண்டறியுங்கள்.',
    'whatToExpect.after.title': 'அறுவை சிகிச்சைக்குப் பின்',
    'whatToExpect.after.description': 'மீட்பு அறையில் என்ன நடக்கும், பொதுவான பக்க விளைவுகள், வலி மேலாண்மை உத்திகள், மற்றும் நீங்கள் எப்போது இயல்பு வாழ்க்கைக்குத் திரும்பலாம் என்பதைக் கண்டறியுங்கள்.',
    'whatToExpect.learnMore': 'மேலும் அறிக',
    
    // Before Surgery Page Translations - Tamil
    'before.title': 'அறுவைச் சிகிச்சைக்கு முன்',
    'before.intro': 'உங்கள் செயல்முறைக்கு முன் என்ன எதிர்பார்க்கலாம் என்பதைப் புரிந்துகொள்வது பதற்றத்தைக் குறைக்கவும் சிறந்த முடிவைப் பெறவும் உதவும்.',
    'before.qa1.question': 'அறுவைச் சிகிச்சைக்கு முந்தைய மதிப்பீடு என்றால் என்ன?',
    'before.qa1.answer1': 'இது உங்கள் மருத்துவ வரலாறு, உடல் பரிசோதனை, இரத்தப் பரிசோதனைகள், ECG மற்றும் பிற ஆய்வுகளை உள்ளடக்கியது. இதன் நோக்கம், மயக்க மருந்து கொடுப்பதற்கு முன் ஏற்படக்கூடிய அபாயங்களைக் கண்டறிந்து, உங்கள் உடல்நிலையை சிறந்த முறையில் தயார் செய்வதாகும்.',
    'before.qa1.answer2': 'இந்த மதிப்பீட்டின் போது, உங்கள் மயக்க மருந்து நிபுணர்:',
    'before.qa1.list1': 'உங்கள் மருத்துவ வரலாறு மற்றும் முந்தைய அறுவை சிகிச்சைகளை மதிப்பாய்வு செய்வார்',
    'before.qa1.list2': 'ஒவ்வாமை மற்றும் தற்போதைய மருந்துகளைப் பற்றி கேட்பார்',
    'before.qa1.list3': 'உங்கள் இதயம் மற்றும் நுரையீரல்களில் கவனம் செலுத்தி உடல் பரிசோதனையை மேற்கொள்வார்',
    'before.qa1.list4': 'இரத்த வேலை மற்றும் ECG உட்பட சோதனை முடிவுகளை மதிப்பீடு செய்வார்',
    'before.qa1.list5': 'மயக்க மருந்து திட்டத்தை விவாதித்து உங்கள் கேள்விகளுக்கு பதிலளிப்பார்',
    'before.qa2.question': 'உணவு அருந்தாமல் இருப்பது (விரதம்) ஏன் அவசியம்?',
    'before.qa2.answer1': 'மயக்க நிலையில் இருக்கும்போது, வயிற்றில் உள்ள உணவுப் பொருட்கள் நுரையீரலுக்குள் செல்லும் அபாயத்தைக் குறைப்பதற்காகவே இது தேவைப்படுகிறது. .',
    'before.qa2.guidelines': 'வழிகாட்டுதல்கள்:',
    'before.qa2.list1': 'திட உணவுகள் மற்றும் பால்: அறுவைச் சிகிச்சைக்கு 6 மணி நேரத்திற்கு முன் நிறுத்தவும்',
    'before.qa2.list2': 'தெளிவான திரவங்கள் (தண்ணீர், பால் இல்லாத தேநீர்): அறுவைச் சிகிச்சைக்கு 2 மணி நேரத்திற்கு முன் நிறுத்தவும்',
    'before.qa2.siptitle': 'சிப் டில் செண்ட் திட்டம்:',
    'before.qa2.siptext1': 'பல மருத்துவமனைகள் இப்போது அறுவைச் சிகிச்சைக்கு 2 மணி நேரத்திற்கு முன் வரை தெளிவான திரவங்களைக் குடிக்க நோயாளிகளை ஊக்குவிக்கின்றன. இது நீரிழப்பைத் தடுக்க உதவுகிறது மற்றும் உங்கள் மீட்பை மேம்படுத்தலாம். "சிப் டில் செண்ட்" நெறிமுறை பற்றி உங்கள் சுகாதார வழங்குநரிடம் கேளுங்கள்.',
    'before.qa2.siptext2': 'சிப் டில் செண்ட் உணவு தவிர்ப்பு தகவலைப் பற்றி மேலும் அறிக',
    'before.qa3.question': 'எந்த மருந்துகளைத் தவிர்க்க வேண்டும்?',
    'before.qa3.answer1': 'சில மருந்துகள் மயக்க மருந்தை இடையூறு செய்யலாம் அல்லது அறுவை சிகிச்சையில் இரத்தப்போக்கு அபாயத்தை அதிகரிக்கலாம். •	நீங்கள் உட்கொள்ளும் அனைத்து மருந்துகள் குறித்தும் உங்கள் மயக்க மருந்து நிபுணரிடம் முன்கூட்டியே தெளிவாகக் கலந்தாலோசிப்பது மிகவும் அவசியம்..',
    'before.qa3.subtitle': 'நிறுத்த வேண்டிய அல்லது சரிசெய்ய வேண்டிய மருந்துகளில் அடங்கும்:',
    'before.qa3.list1': '•	பொதுவான இரத்தம் நீர்க்கச் செய்யும் மருந்துகள் (Blood-thinners): Aspirin, clopidogrel, warfarin.',
    'before.qa3.list2': 'NSAIDகள்: ஐபுப்ரோஃபென், டைக்லோஃபெனாக்',
    'before.qa3.list3': 'மூலிகை நிரப்புகள்: ஜிங்கோ, பூண்டு, மீன் எண்ணெய்',
    'before.qa3.important': 'முக்கியம்: உங்கள் மருத்துவர் அல்லது மயக்க மருந்து நிபுணரை முதலில் கலந்தாலோசிக்காமல் மருந்துகளை எப்போதும் நிறுத்தாதீர்கள்.',
    'before.qa4.question': 'மன ரீதியாகவும் உடல் ரீதியாகவும் எப்படி தயாராவது?',
    'before.qa4.physical': 'உடல் ரீதியாக தயாராதல்:',
    'before.qa4.plist1': 'அறுவைச் சிகிச்சைக்கு முன் நன்கு தூங்கவும்',
    'before.qa4.plist2': 'விரதம் தொடங்கும் வரை போதுமான அளவு நீர் அருந்தவும்.',
    'before.qa4.plist3': 'உங்கள் அறுவை சிகிச்சை குழுவில் இருந்து ஏதேனும் குறிப்பிட்ட அறிவுறுத்தல்களைப் பின்பற்றவும்',
    'before.qa4.plist4': 'அறுவைச் சிகிச்சைக்கு முன் குறைந்தது 24 மணி நேரத்திற்கு மது அருந்துவதைத் தவிர்க்கவும்',
    'before.qa4.plist5': 'நீங்கள் புகைத்தால், அறுவைச் சிகிச்சைக்கு முன் நிறுத்த அல்லது புகைப்பதைக் குறைக்க முயற்சிக்கவும்',
    'before.qa4.mental': 'மன ரீதியாக தயாராவது:',
    'before.qa4.mlist1': 'ஏதேனும் கவலைகளைத் தீர்க்க அறுவை சிகிச்சைக்கு முந்தைய மதிப்பீட்டின் போது கேள்விகளைக் கேளுங்கள்',
    'before.qa4.mlist2': 'ஆழ்ந்த சுவாசம் அல்லது தியானம் போன்ற தளர்வு நுட்பங்களைப் பயிற்சி செய்யுங்கள்',
    'before.qa4.mlist3': 'மருத்துவமனைக்கு ஆறுதல் தரும் பொருட்களைக் கொண்டு வாருங்கள் (மருத்துவமனை வழிகாட்டுதல்களுக்குள்)',
    'before.qa4.mlist4': 'வெளியேற்றப்பட்ட பிறகு குடும்பத்தினர் அல்லது நண்பர்களின் ஆதரவை ஏற்பாடு செய்யுங்கள்',
    'before.qa4.practical': 'நடைமுறை தயாரிப்புகள்:',
    'before.qa4.prlist1': 'மருத்துவமனைக்கு போக்குவரத்து ஏற்பாடு செய்யுங்கள்',
    'before.qa4.prlist2': 'உங்கள் வீட்டிற்கு திரும்பும்போது உங்கள் வீட்டைத் தயார் செய்யுங்கள் (எளிதான உணவுகள், வசதியான மீட்பு பகுதி)',
    'before.qa4.prlist3': 'உங்கள் மருந்துகள், ஒவ்வாமைகள் மற்றும் முந்தைய மயக்க மருந்து அனுபவங்களின் பட்டியலைக் கொண்டு வாருங்கள்',
    'before.qa4.prlist4': 'அறுவை சிகிச்சைக்கு முன் நகைகள், மேக்கப் மற்றும் நெயில் பாலிஷை அகற்றவும்',
    'before.qa4.prlist5': 'அறுவை சிகிச்சைக்கு முன் குளிப்பது பற்றிய குறிப்பிட்ட வழிமுறைகளைப் பின்பற்றவும்',
    
    // During Surgery Translations - Tamil
    'during.title': 'அறுவை சிகிச்சையின்போது',
    'during.intro': 'அறுவை சிகிச்சையின்போது என்ன நடக்கிறது மற்றும் மயக்க மருந்து எவ்வாறு செயல்படுகிறது என்பதைப் புரிந்துகொள்வது உங்கள் பதற்றத்தைக் குறைத்து, செயல்முறைக்குத் தயாராவதற்கும் உதவலாம்.',
    'during.qa1.question': 'மயக்க மருந்தின் வகைகள் என்ன?',
    'during.qa1.general': '**பொது மயக்க மருந்து (GA):**',
    'during.qa1.generalDesc': 'மருந்துகள் மூலம் தூண்டப்படும் நினைவற்ற நிலை. உங்கள் அறுவை சிகிச்சையின்போது நீங்கள் முற்றிலும் சுயநினைவின்றி இருப்பீர்கள் மற்றும் வலியை உணர முடியாது.',
    'during.qa1.generalUse': '**பொதுவாகப் பயன்படுத்தப்படுவது:** முக்கிய அறுவை சிகிச்சைகள், உடல் குழிகளில் செய்யப்படும் செயல்முறைகள் அல்லது பிற வகைகள் பொருத்தமாக இல்லாதபோது.',
    'during.qa1.spinal': '**தண்டுவடம்/எபிடியூரல் மயக்க மருந்து:**',
    'during.qa1.spinalDesc': 'இடுப்புக்குக் கீழே உள்ள நரம்புகள் செயலிழக்கச் செய்ய, சப்அரக்னாய்டு இடத்தில் (தண்டுவட எலும்புக்கு அருகில்) அல்லது எபிடியூரல் இடத்தில் உள்ளூர் மயக்க மருந்து செலுத்தப்படுகிறது.',
    'during.qa1.spinalUse': '**பொதுவாகப் பயன்படுத்தப்படுவது:** கீழ் உடல் செயல்முறைகள், அறுவை சிகிச்சை மூலம் குழந்தை பிறப்பு, இடுப்பு/முழங்கால் அறுவை சிகிச்சை.',
    'during.qa1.nerve': '**புற நரம்பு தடுப்புகள்:**',
    'during.qa1.nerveDesc': 'உடலின் குறிப்பிட்ட ஒரு பகுதியை மரத்துப்போகச் செய்ய, குறிப்பிட்ட நரம்புகளுக்கு அருகில் உள்ளூர் மயக்க மருந்து செலுத்தப்படுகிறது.',
    'during.qa1.nerveUse': '**பொதுவாகப் பயன்படுத்தப்படுவது:** கை, தோள்பட்டை அல்லது கால் அறுவை சிகிச்சைகள்; குறிப்பிட்ட வலி நிவாரணத்தை அளிக்கிறது.',
    'during.qa1.sedation': '**விழிப்புணர்வு மயக்கம் (கண்காணிக்கப்பட்ட மயக்க மருந்து பராமரிப்பு):**',
    'during.qa1.sedationDesc': 'விழிப்புணர்வைப் பராமரிக்கும் அதே வேளையில் நீங்கள் தளர்வாக இருக்கவும், வலியைக் குறைக்கவும் உதவும் மருந்துகள்.',
    'during.qa1.sedationUse': '**பொதுவாகப் பயன்படுத்தப்படுவது:** சிறிய செயல்முறைகள், எண்டோஸ்கோபிகள், பல் சிகிச்சை.',

    'during.qa2.question': 'ஒவ்வொரு வகையான மயக்க மருந்தும் எவ்வாறு செயல்படுகிறது?',
    'during.qa2.general': '**பொது மயக்க மருந்து இயக்கவியல்:**',
    'during.qa2.generalDesc': 'பொது மயக்க மருந்து பின்வரும் மருந்துகளின் கலவையால் செயல்படுகிறது:',
    'during.qa2.generalList1': 'நினைவற்ற நிலையைத் தூண்டுகிறது (**ப்ரொபோஃபோல், தயோபெண்டல்**)',
    'during.qa2.generalList2': 'நினைவற்ற நிலையைப் பராமரிக்கிறது (**சேவோஃப்ளூரேன், டெஸ்ஃப்ளூரேன் வாயுக்கள்**)',
    'during.qa2.generalList3': 'தசைகளைத் தளர்த்துகிறது (**ரோக்குரோனியம், சக்சினைல்கோலைன்**)',
    'during.qa2.generalList4': 'வலியைத் தடுக்கிறது (**ஃபெண்டானில், மார்ஃபின்**)',
    'during.qa2.generalEnd': 'இந்த மருந்துகள் உங்கள் மத்திய நரம்பு மண்டலத்தை ஒரு கட்டுப்படுத்தப்பட்ட முறையில் மந்தப்படுத்துகின்றன, மாற்றக்கூடிய நினைவற்ற நிலையை உருவாக்க வெவ்வேறு மூளை ஏற்பிகளைப் பாதிக்கின்றன.',
    'during.qa2.spinal': '**தண்டுவடம்/எபிடியூரல் இயக்கவியல்:**',
    'during.qa2.spinalDesc': 'உள்ளூர் மயக்க மருந்து (**புபிவகேன் போன்றது**) தண்டுவட கோர்ட்டுக்கு (spinal cord) அருகே செலுத்தப்படுகிறது:',
    'during.qa2.spinalList1': '**தண்டுவடம்:** நேரடியாக தண்டுவட கோர்ட்டைச் சுற்றியுள்ள மூளைத் திரவத்தில்.',
    'during.qa2.spinalList2': '**எபிடியூரல்:** தண்டுவட உறைகளுக்கு வெளியே உள்ள இடத்தில்.',
    'during.qa2.spinalEnd': 'இந்த மருந்து நரம்பு சவ்வுகளில் உள்ள சோடியம் சேனல்களைத் தடுக்கிறது, நரம்பு துடிப்புகள் தண்டுவடத்திலிருந்து மூளைக்குச் செல்வதைத் தடுக்கிறது.',
    'during.qa2.nerve': '**புற நரம்பு தடுப்பு இயக்கவியல்:**',
    'during.qa2.nerveDesc': 'அல்ட்ராசவுண்ட் வழிகாட்டுதலைப் பயன்படுத்தி, மயக்க மருந்து நிபுணர்கள் குறிப்பிட்ட நரம்புக் கற்றைகளைச் சுற்றி உள்ளூர் மயக்க மருந்தைச் செலுத்துகிறார்கள். மருந்து சுயநினைவைப் பாதிக்காமல் அந்த குறிப்பிட்ட பகுதியில் நரம்புப் பரவலைத் தற்காலிகமாகத் தடுக்கிறது.',
    'during.qa2.sedation': '**மயக்க இயக்கவியல்:**',
    'during.qa2.sedationDesc': 'மிடசோலம் (ஒரு பென்சோடியாசபைன்) மற்றும் ஃபெண்டானில் (ஒரு ஓபியாய்டு) போன்ற மருந்துகளின் கவனமாக அளவிடப்பட்ட அளவுகள் பின்வருவனவற்றை உருவாக்குகின்றன:',
    'during.qa2.sedationList1': 'பதற்றத்தைக் குறைத்தல்',
    'during.qa2.sedationList2': 'வலி உணர்வைக் குறைத்தல்',
    'during.qa2.sedationList3': 'நினைவாற்றல் குறைவு (செயல்முறையின் நினைவுகள் குறைவு)',
    'during.qa2.sedationList4': 'விழிப்புணர்வு மற்றும் பாதுகாப்பு அனிச்சை செயல்களைப் பராமரித்தல்',

    'during.qa3.question': 'மயக்க மருந்தின் அபாயங்கள் மற்றும் சிக்கல்கள், தடுப்பு மற்றும் மேலாண்மை',
    'during.qa3.minor': '**பொதுவான சிறிய விளைவுகள்:**',
    'during.qa3.minorList1': '**நடுக்கம்** (20%) - சூடான போர்வைகளால் தடுக்கப்படுகிறது.',
    'during.qa3.minorList2': '**அறுவை சிகிச்சைக்குப் பின் குமட்டல் மற்றும் வாந்தி** (25%) - ஓண்டான்செட்ரான் போன்ற வாந்தி எதிர்ப்பு மருந்துகளால் நிர்வகிக்கப்படுகிறது.',
    'during.qa3.minorList3': '**தொண்டை வலி** (15%) - சுவாசக் குழாய் நுழைக்கப்பட்டதால்; மென்மையான வழிகாட்டல் மேலாண்மை மூலம் குறைக்கப்படுகிறது.',
    'during.qa3.minorList4': '**தலைவலி** (10%) - நீரேற்றம் மற்றும் லேசான வலி நிவாரணிகள் மூலம் சிகிச்சையளிக்கப்படுகிறது.',
    'during.qa3.regional': '**பிராந்திய/தண்டுவடம் மயக்க மருந்து அபாயங்கள்:**',
    'during.qa3.regionalList1': '**டியூரல் குத்தியபின் தலைவலி** (1-2%) - நீரேற்றம், காஃபின் அல்லது எபிடியூரல் இரத்த பேட்ச் மூலம் நிர்வகிக்கப்படுகிறது.',
    'during.qa3.regionalList2': '**தற்காலிக நரம்பியல் அறிகுறிகள்** (0.5%) - பொதுவாக நேரத்துடன் தீர்க்கப்படுகிறது.',
    'during.qa3.regionalList3': '**சிறுநீர் தக்கவைப்பு** - தேவைப்பட்டால் தற்காலிக சிறுநீர்க்குழாய் செருகல் (catheterization).',
    'during.qa3.serious': '**தீவிரமான ஆனால் அரிதான சிக்கல்கள்:**',
    'during.qa3.seriousList1': '**அனாஃபிலாக்ஸிஸ்** (10,000 இல் 1) - கண்காணிப்பு மூலம் கண்டறியப்பட்டு எபினெஃப்ரின் மூலம் சிகிச்சையளிக்கப்படுகிறது.',
    'during.qa3.seriousList2': '**தீவிர ஹைபர்தெர்மியா** (< 50,000 இல் 1) - டேன்ட்ரோலின் மூலம் சிகிச்சையளிக்கப்படும் மரபணு நிலை.',
    'during.qa3.seriousList3': '**நிரந்தர நரம்பு காயம்** (< 100,000 இல் 1) - கவனமான நிலைப்படுத்துதல் மற்றும் நுட்பத்தால் தடுக்கப்படுகிறது.',
    'during.qa3.seriousList4': '**பொது மயக்க மருந்தின்போது விழிப்புணர்வு** (< 1,000 இல் 1) - BIS தொழில்நுட்பத்தைப் பயன்படுத்தி கண்காணிக்கப்படுகிறது.',
    'during.qa3.airway': '**சுவாசப்பாதை சிக்கல்கள்:**',
    'during.qa3.airwayList1': '**குழாய் நுழைத்தல் கடினம்** (1-3%) - சிறப்பு உபகரணங்கள் மற்றும் நுட்பங்களுடன் நிர்வகிக்கப்படுகிறது.',
    'during.qa3.airwayList2': '**ஆஸ்பிரேஷன்** (< 1%) - உணவு தவிர்ப்பு மற்றும் விரைவான வரிசை தூண்டுதல் மூலம் தடுக்கப்படுகிறது.',
    'during.qa3.airwayList3': '**பல் சேதம்** (< 0.5%) - கவனமான நுட்பத்தால் குறைக்கப்படுகிறது.',
    'during.qa3.remember': 'நினைவில் கொள்ளுங்கள்: இந்தச் சிக்கல்களைத் தடுக்கவும், கண்டறியவும், நிர்வகிக்கவும் உங்கள் மயக்க மருந்து நிபுணர் **மிகவும் பயிற்சி பெற்றவர்**. பெரும்பாலான மயக்க மருந்துகள் எந்த தீவிரப் பிரச்சனைகளும் இல்லாமல் நிர்வகிக்கப்படுகின்றன.',

    'during.qa4.question': 'கண்காணிப்பு மற்றும் பாதுகாப்பு நடவடிக்கைகள்',
    'during.qa4.standard': '**நிலையான கண்காணிப்புகள் (ASA வழிகாட்டுதல்கள்):**',
    'during.qa4.standardList1': '**ECG** - இதய துடிப்பு மற்றும் ரிதத்தைக் கண்காணிக்கிறது.',
    'during.qa4.standardList2': '**NIBP** - ஊடுருவாத இரத்த அழுத்தம், பொதுவாக ஒவ்வொரு 3-5 நிமிடங்களுக்கும் அளவிடப்படுகிறது.',
    'during.qa4.standardList3': '**SpO₂** - நாடி ஆக்ஸிமீட்டர் மூலம் ஆக்ஸிஜன் செறிவு.',
    'during.qa4.standardList4': '**ETCO₂** - சரியான சுவாசத்தை உறுதிப்படுத்த, சுவாச முடிவில் உள்ள கார்பன் டை ஆக்சைடு அளவு.',
    'during.qa4.standardList5': '**வெப்பநிலை** - ஹைபோதெர்மியா (குறைந்த உடல் வெப்பநிலை) அல்லது ஹைபர்தெர்மியா (அதிக உடல் வெப்பநிலை) கண்டறியவும் தடுக்கவும்.',
    'during.qa4.advanced': '**மேம்பட்ட கண்காணிப்பு (தேவைப்படும்போது):**',
    'during.qa4.advancedList1': '**தமனிக் கோடு** - தொடர்ச்சியான இரத்த அழுத்த கண்காணிப்புக்கு.',
    'during.qa4.advancedList2': '**மைய சிரை அழுத்தம்** - சிக்கலான அல்லது நெருக்கடியான நோயாளிகளுக்கு.',
    'during.qa4.advancedList3': '**நரம்பு-தசை தடுப்பு கண்காணிப்புகள்** - பொருத்தமான தசை தளர்வை உறுதிசெய்ய.',
    'during.qa4.advancedList4': '**BIS (பைஸ்பெக்டிரல் குறியீடு)** - மயக்க மருந்தின் ஆழத்தைக் கண்காணிக்க.',
    'during.qa4.targets': '**சாதாரண இலக்கு மதிப்புகள்:**',
    'during.qa4.targetsList1': '**SpO₂:** > 95%',
    'during.qa4.targetsList2': '**ETCO₂:** 35-45 mmHg',
    'during.qa4.targetsList3': '**MAP (சராசரி தமனி அழுத்தம்):** 65-90 mmHg',
    'during.qa4.targetsList4': '**வெப்பநிலை:** 36-37°C (97-99°F)',
    'during.qa4.safety': '**பாதுகாப்பு நெறிமுறைகள்:**',
    'during.qa4.safetyList1': 'தரப்படுத்தப்பட்ட சரிபார்ப்பு பட்டியல்களைப் பயன்படுத்தி மயக்க மருந்து உபகரணச் சோதனைகள்.',
    'during.qa4.safetyList2': 'அறுவை சிகிச்சை தொடங்குவதற்கு முன் WHO அறுவை சிகிச்சை பாதுகாப்பு சரிபார்ப்பு பட்டியல்.',
    'during.qa4.safetyList3': 'அவசர மருந்துகள் மற்றும் உபகரணங்களை உடனடியாக அணுகுதல்.',
    'during.qa4.safetyList4': 'முக்கியமான விலகல்களுக்கு தொடர்ச்சியான காட்சி மற்றும் ஒலி எச்சரிக்கைகள்.',
    'during.qa4.safetyList5': 'சரியான சுவாசக் குழாய் வைப்பிடத்தை உறுதிப்படுத்த **கேப்னோகிராஃபி** (Capnography).',
    'during.qa4.modern': 'நவீன மயக்க மருந்து கண்காணிப்பு பாதுகாப்பை கணிசமாக மேம்படுத்தியுள்ளது. உங்கள் உயிர்நாடிகள் தொடர்ந்து காட்டப்பட்டு, உங்கள் செயல்முறை முழுவதும் உங்கள் மயக்க மருந்து குழுவால் கண்காணிக்கப்படுகின்றன.',

    'during.qa5.question': 'அறுவை சிகிச்சையின்போது மயக்க மருந்து நிபுணரின் பங்கு',
    'during.qa5.intro': 'உங்கள் மயக்க மருந்து நிபுணர் என்பவர் அறுவை சிகிச்சை முழுவதும் உங்கள் பாதுகாப்பு மற்றும் ஆசுவாசத்தில் மட்டுமே கவனம் செலுத்தி உங்களுடன் இருக்கும் சிறப்புப் பயிற்சி பெற்ற மருத்துவர்.',
    'during.qa5.responsibilities': 'மயக்க மருந்து நிபுணரின் பொறுப்புகளில் அடங்கும்:',
    'during.qa5.respList1': 'உங்கள் உயிர்நாடிகள், மயக்க மருந்து ஆழம், வலி கட்டுப்பாடு மற்றும் திரவ நிலை பற்றிய **தொடர்ச்சியான மதிப்பீடு**.',
    'during.qa5.respList2': 'அறுவை சிகிச்சை முழுவதும் உங்கள் தேவைகள் மற்றும் அறுவை சிகிச்சைத் தேவைகளின் அடிப்படையில் **மருந்து சரிசெய்தல்**.',
    'during.qa5.respList3': 'இரத்த அழுத்த மாற்றங்கள், அரித்மியாஸ் அல்லது இரத்தப்போக்கு போன்ற **எதிர்பாராத நிகழ்வுகளை நிர்வகித்தல்**.',
    'during.qa5.respList4': 'நேரம், நிலைப்படுத்துதல் மற்றும் சிறப்புத் தேவைகள் குறித்து **அறுவை சிகிச்சை நிபுணர்களுடன் ஒருங்கிணைத்தல்**.',
    'during.qa5.respList5': 'நோயாளியின் நலன்களைக் காத்தல்: உங்கள் பாதுகாப்பு, கண்ணியம் மற்றும் ஆசுவாசம் எப்போதும் உறுதிசெய்தல்.',
    'during.qa5.respList6': 'இரத்த மாற்றம், திரவ மேலாண்மை மற்றும் வலி கட்டுப்பாடு பற்றிய **மருத்துவ முடிவுகளை எடுத்தல்**.',
    'during.qa5.team': '**குழு அணுகுமுறை:**',
    'during.qa5.teamDesc': 'உங்கள் மயக்க மருந்து நிபுணர் பெரும்பாலும் ஒரு குழுவுடன் பணியாற்றுகிறார், அதில் அடங்கலாம்:',
    'during.qa5.teamList1': 'மயக்க மருந்து உதவியாளர்கள் அல்லது தொழில்நுட்ப வல்லுநர்கள்',
    'during.qa5.teamList2': 'மயக்க மருந்து செவிலியர்கள் (சில நாடுகளில்)',
    'during.qa5.teamList3': 'மேற்பார்வையின் கீழ் மயக்க மருந்து பயிற்சியாளர்கள்',
    'during.qa5.think': 'உங்கள் மயக்க மருந்து நிபுணரை அறுவை சிகிச்சையின்போது உங்கள் தனிப்பட்ட "உயிர் செயல்பாடுகள் மேலாளர்" என்று நினைத்துக் கொள்ளுங்கள்; நீங்கள் நினைவற்ற நிலையில் அல்லது மயக்கப்பட்ட நிலையில் இருக்கும்போது உங்கள் உடலின் அமைப்புகள் நிலையாக இருப்பதை உறுதிசெய்ய அவர் தொடர்ந்து கண்காணித்து சரிசெய்கிறார்',
    
    // After Surgery Translations - Tamil
    'after.title': 'அறுவை சிகிச்சைக்குப் பின்',
    'after.intro': 'உங்கள் அறுவை சிகிச்சைக்குப் பின் என்ன எதிர்பார்க்கலாம் என்பதைப் புரிந்துகொள்வது மீட்புக்குத் தயாராக உதவும், மேலும் சாதாரண மற்றும் அசாதாரண அறிகுறிகளை அடையாளம் காணவும் உதவும்.',
    'after.qa1.question': 'மீட்பு அறையில் என்ன நடக்கும்?',
    'after.qa1.intro': 'அறுவை சிகிச்சைக்குப் பிறகு, நீங்கள் மீட்பு அறை என்றும் அழைக்கப்படும் **மயக்க மருந்துக்குப் பிந்தைய பராமரிப்புப் பிரிவுக்கு (PACU)** மாற்றப்படுவீர்கள். இது நீங்கள் மயக்க மருந்திலிருந்து வெளிவரும்போது நெருக்கமாகக் கண்காணிக்கப்படும் ஒரு சிறப்புப் பகுதியாகும்.',
    'after.qa1.expect': 'PACU-இல், நீங்கள் எதிர்பார்க்கலாம்:',
    'after.qa1.monitoring': '**தொடர்ச்சியான கண்காணிப்பு:**',
    'after.qa1.monitoringDesc': 'உங்கள் உயிர்நாடிகள் (இரத்த அழுத்தம், இதய துடிப்பு, ஆக்ஸிஜன் அளவுகள்) தொடர்ந்து கண்காணிக்கப்படும்.',
    'after.qa1.nursing': '**ஒன்றுக்கு ஒன்று செவிலியர் பராமரிப்பு:**',
    'after.qa1.nursingDesc': 'நீங்கள் முழுமையாக விழித்து, நிலையாக இருக்கும் வரை.',
    'after.qa1.assessments': '**வழக்கமான மதிப்பீடுகள்:**',
    'after.qa1.assessmentsDesc': 'உங்கள் வலி அளவுகள் மற்றும் தேவையான வலி மருந்து நிர்வாகம் குறித்து.',
    'after.qa1.oxygen': '**ஆக்ஸிஜன் சிகிச்சை:**',
    'after.qa1.oxygenDesc': 'தேவைப்பட்டால் முக மூடி அல்லது மூக்கு வழியே.',
    'after.qa1.warming': '**சூடான போர்வைகள்:**',
    'after.qa1.warmingDesc': 'நீங்கள் குளிராக உணர்ந்தால் அல்லது நடுங்கினால்.',
    'after.qa1.iv': '**IV திரவங்கள்:**',
    'after.qa1.ivDesc': 'நீங்கள் வாய்வழியாக திரவம் அருந்தும் வரை.',
    'after.qa1.howLong': 'நான் மீட்புப் பிரிவில் எவ்வளவு நேரம் இருப்பேன்?',
    'after.qa1.timeFrame': 'பெரும்பாலான நோயாளிகள் PACU-இல் **30 நிமிடங்கள் முதல் 2 மணி நேரம் வரை** இருப்பார்கள், இது பின்வருவனவற்றைப் பொறுத்தது:',
    'after.qa1.timeList1': 'நீங்கள் பெற்ற அறுவை சிகிச்சை மற்றும் மயக்க மருந்து வகை.',
    'after.qa1.timeList2': 'நீங்கள் எவ்வளவு விரைவாக விழித்தெழுந்து நிலையாகிறீர்கள்.',
    'after.qa1.timeList3': 'உங்கள் வலி மற்றும் குமட்டல் எவ்வளவு நன்றாகக் கட்டுப்படுத்தப்படுகிறது.',
    'after.qa1.timeList4': 'அறுவை சிகிச்சையின்போது ஏதேனும் சிக்கல்கள் இருந்ததா.',
    'after.qa1.transfer': 'மீட்புக் குழு உங்கள் நிலையில் திருப்தி அடைந்தவுடன், நீங்கள் வார்டுக்கு மாற்றப்படுவீர்கள் அல்லது வீட்டிற்கு அனுப்பப்படுவீர்கள்.',

    'after.qa2.question': 'பொதுவான அறுவை சிகிச்சைக்குப் பிந்தைய பக்க விளைவுகள் மற்றும் வலி கட்டுப்பாடு',
    'after.qa2.sideEffects': '**பொதுவான பக்க விளைவுகள்:**',
    'after.qa2.throat': '**தொண்டை வலி:**',
    'after.qa2.throatDesc': '- சுவாசக் குழாய் நுழைக்கப்பட்டதால்; பொதுவாக 24-48 மணிநேரத்திற்குள் தீர்க்கப்படும்.',
    'after.qa2.nausea': '**குமட்டல் மற்றும் வாந்தி:**',
    'after.qa2.nauseaDesc': '- மருந்துகள் மூலம் சிகிச்சையளிக்கலாம்.',
    'after.qa2.dizziness': '**தலைச்சுற்றல்:**',
    'after.qa2.dizzinessDesc': '- பொதுவாக மெதுவாக அசைவதாலும், நீர் அருந்துவதாலும் மேம்படும்.',
    'after.qa2.drowsiness': '**தூக்கம்:**',
    'after.qa2.drowsinessDesc': '- மயக்க மருந்து குறையும்போது படிப்படியாக மேம்படும்.',
    'after.qa2.shivering': '**நடுக்கம்:**',
    'after.qa2.shiveringDesc': '- பொதுவாக தற்காலிகமானது; சூடான போர்வைகளால் சிகிச்சையளிக்கப்படும்.',
    'after.qa2.confusion': '**குழப்பம்:**',
    'after.qa2.confusionDesc': '- வயதானவர்களில் மிகவும் பொதுவானது; பொதுவாக தற்காலிகமானது.',
    'after.qa2.painManagement': '**வலி மேலாண்மை விருப்பங்கள்:**',
    'after.qa2.ivPain': '**IV வலி மருந்துகள்:**',
    'after.qa2.ivPainDesc': '- உடனடி நிவாரணத்திற்கு பெரும்பாலும் மார்ஃபின் போன்ற ஓபியாய்டுகள்.',
    'after.qa2.pca': '**நோயாளி-கட்டுப்படுத்தப்பட்ட வலி நிவாரணி (PCA):**',
    'after.qa2.pcaDesc': '- ஒரு பொத்தானை அழுத்துவதன் மூலம் வலி மருந்தின் சிறிய அளவுகளை நீங்களே செலுத்த அனுமதிக்கிறது.',
    'after.qa2.oral': '**வாய்வழி வலி மருந்துகள்:**',
    'after.qa2.oralDesc': '- நீங்கள் திரவங்களைக் குடிக்கக்கூடியபோது மாத்திரைகள் அல்லது திரவங்கள்.',
    'after.qa2.blocks': '**பிராந்திய தடுப்புகள்:**',
    'after.qa2.blocksDesc': '- அறுவை சிகிச்சைக்குப் பிறகு பல மணிநேரங்கள் வலி நிவாரணத்தை வழங்கத் தொடரலாம்.',
    'after.qa2.local': '**உள்ளூர் மயக்க மருந்து ஊடுருவல்:**',
    'after.qa2.localDesc': '- அறுவை சிகிச்சை தளத்தைச் சுற்றி செலுத்தப்பட்டது.',
    'after.qa2.nonMed': '**மருந்து அல்லாத நுட்பங்கள்:**',
    'after.qa2.nonMedDesc': '- பனிக்கட்டி ஒத்தடம், சரியான நிலைப்படுத்துதல், தளர்வு நுட்பங்கள்.',
    'after.qa2.tips': '**முக்கியமான வலி மேலாண்மை குறிப்புகள்:**',
    'after.qa2.tipsList1': 'வலி நிவாரணத்தைக் கோருவதற்கு முன் வலி கடுமையாகும் வரை காத்திருக்க வேண்டாம்.',
    'after.qa2.tipsList2': 'சுகாதார ஊழியர்கள் கேட்கும்போது உங்கள் வலியை **0-10 அளவில் மதிப்பிடுங்கள்**.',
    'after.qa2.tipsList3': 'வலி மருந்து வேலை செய்யவில்லை அல்லது விரைவில் அதன் விளைவு முடிந்தால் உங்கள் செவிலியர்களிடம் சொல்லுங்கள்.',
    'after.qa2.tipsList4': 'வலி மருந்துகளிலிருந்து ஏதேனும் **அசாதாரண அறிகுறிகள் அல்லது பக்க விளைவுகளைப் புகாரளிக்கவும்**.',

    'after.qa3.question': 'எப்போது சாப்பிடலாம் மற்றும் குடிக்கலாம்?',
    'after.qa3.intro': 'அறுவை சிகிச்சைக்குப் பிறகு உணவு உண்ணுதல் மற்றும் நீர் அருந்துதல் ஆகியவை அறுவை சிகிச்சையின் வகை, பயன்படுத்தப்படும் மயக்க மருந்து மற்றும் உங்கள் தனிப்பட்ட மீட்பு உட்பட பல காரணிகளைப் பொறுத்தது.',
    'after.qa3.guidelines': '**பொது வழிகாட்டுதல்கள்:**',
    'after.qa3.fluids': '**தெளிவான திரவங்கள்**',
    'after.qa3.fluidsDesc': '(தண்ணீர், ஆப்பிள் ஜூஸ்) - பொதுவாக முழுமையாக விழித்தபின் 2-4 மணிநேரத்திற்குள் அனுமதிக்கப்படுகிறது, நீங்கள் பாதுகாப்பாக விழுங்கியதும்.',
    'after.qa3.light': '**லேசான உணவுகள்**',
    'after.qa3.lightDesc': '(கிராக்கர்கள், டோஸ்ட், சூப்) - பொதுவாக நீங்கள் திரவங்களை நன்றாக சகித்துக்கொள்ளும்போது அனுமதிக்கப்படுகிறது, பெரும்பாலும் அறுவை சிகிச்சைக்குப் பிறகு 4-6 மணிநேரம்.',
    'after.qa3.regular': '**வழக்கமான உணவு**',
    'after.qa3.regularDesc': '- பொதுவாக சகித்துக்கொள்ளப்படும்போது படிப்படியாக மீண்டும் தொடங்கப்படுகிறது, பெரும்பாலும் சிறிய அறுவை சிகிச்சைகளுக்கு அடுத்த நாள்.',
    'after.qa3.considerations': '**சிறப்பு கவனக் குறிப்புகள்:**',
    'after.qa3.abdominal': '**வயிற்று அறுவை சிகிச்சை:**',
    'after.qa3.abdominalDesc': '- குடல் ஒலிகள் திரும்பும் வரை மற்றும் வாயு அல்லது மலம் கழிக்கும் வரை காத்திருக்க வேண்டியிருக்கலாம்.',
    'after.qa3.throat': '**தொண்டை அல்லது வாய் அறுவை சிகிச்சை:**',
    'after.qa3.throatDesc': '- சிறப்பு உணவு கட்டுப்பாடுகள் தேவைப்படலாம்.',
    'after.qa3.nausea': '**குமட்டல் அல்லது வாந்தி:**',
    'after.qa3.nauseaDesc': '- அறிகுறிகள் மேம்படும் வரை சாப்பிடுவதற்குத் திரும்புவதைத் தாமதப்படுத்தலாம்.',
    'after.qa3.medications': '**சில மருந்துகள்:**',
    'after.qa3.medicationsDesc': '- உணவுடன் எடுக்க வேண்டியிருக்கலாம், நீங்கள் அவற்றை மீண்டும் தொடங்கும் போது இது பாதிக்கும்.',
    'after.qa3.always': 'உங்கள் அறுவை சிகிச்சைக்குப் பிறகு உணவு உண்ணுதல் மற்றும் நீர் அருந்துவது பற்றிய உங்கள் சுகாதார வழங்குநரின் **குறிப்பிட்ட அறிவுறுத்தல்களைப் எப்போதும் பின்பற்றுங்கள்.** மெதுவாகத் தொடங்கி, சகித்துக்கொள்ளப்படும்போது படிப்படியாக அதிகரிக்கவும்.',

    'after.qa4.question': 'மருத்துவமனையிலிருந்து வெளியேறும் வழிமுறைகள் மற்றும் தொடர் பராமரிப்பு',
    'after.qa4.instructions': '**பொதுவான வெளியேற்ற வழிமுறைகள்:**',
    'after.qa4.activity': '**செயல்பாடு கட்டுப்பாடுகள்:**',
    'after.qa4.activityDesc': '- நீங்கள் சாதாரண செயல்பாடுகள், வாகனம் ஓட்டுதல், வேலை மற்றும் உடற்பயிற்சிக்கு எப்போது திரும்பலாம் என்பது பற்றி.',
    'after.qa4.wound': '**காயப் பராமரிப்பு:**',
    'after.qa4.woundDesc': '- அறுவை சிகிச்சை தளத்தை எவ்வாறு சுத்தம் செய்வது மற்றும் கட்டு போடுவது பற்றி.',
    'after.qa4.medication': '**மருந்து வழிமுறைகள்:**',
    'after.qa4.medicationDesc': '- பரிந்துரைக்கப்பட்ட மருந்துகளை எப்போது மற்றும் எப்படி எடுப்பது பற்றி.',
    'after.qa4.infection': '**தொற்று அறிகுறிகள்:**',
    'after.qa4.infectionDesc': '- எதைப் பார்க்க வேண்டும் (அதிகரித்த வலி, சிவப்பு, வீக்கம், வெளியேற்றம், காய்ச்சல்) என்பது பற்றி.',
    'after.qa4.diet': '**உணவு வழிகாட்டுதல்கள்:**',
    'after.qa4.dietDesc': '- குணமடையும்போது ஏதேனும் சிறப்பு உணவுத் தேவைகள் பற்றி.',
    'after.qa4.showering': '**குளித்தல்:**',
    'after.qa4.showeringDesc': '- அறுவை சிகிச்சை பகுதியை ஈரமாக்குவது எப்போது பாதுகாப்பானது என்பது பற்றி.',
    'after.qa4.contact': '**தொடர்பு தகவல்:**',
    'after.qa4.contactDesc': '- உங்களுக்கு கேள்விகள் அல்லது பிரச்சனைகள் இருந்தால் யாரைத் தொடர்பு கொள்வது என்பது பற்றி.',
    'after.qa4.appointments': '**தொடர் பராமரிப்பு சந்திப்புகள்:**',
    'after.qa4.appointmentsDesc': 'உங்கள் வெளியேற்ற வழிமுறைகளில் அடுத்த சந்திப்புகள் பற்றிய விவரங்கள் இருக்கும். பொதுவாக, உங்களுக்கு பின்வருவன இருக்கும்:',
    'after.qa4.appointmentsList1': 'உங்கள் குணமடைதலைச் சரிபார்க்க உங்கள் அறுவை சிகிச்சை நிபுணருடன் சந்திப்பு.',
    'after.qa4.appointmentsList2': 'ஏதேனும் தையல் அல்லது ஸ்டேப்பிள் அகற்றுவதற்கான வழிமுறைகள்.',
    'after.qa4.appointmentsList3': 'தேவைப்படும் உடல் சிகிச்சை பற்றிய தகவல்.',
    'after.qa4.keepAppts': '**நீங்கள் நன்றாக உணர்ந்தாலும், அனைத்து தொடர் பராமரிப்பு சந்திப்புகளையும் வைத்திருக்க உறுதிப்படுத்திக் கொள்ளுங்கள்.**',
    'after.qa4.seekHelp': '**உடனடி மருத்துவ கவனிப்பைத் தேட வேண்டியபோது:**',
    'after.qa4.seekList1': 'சுவாசிப்பதில் சிரமம் அல்லது மூச்சுத் திணறல்.',
    'after.qa4.seekList2': 'மார்பு வலி அல்லது ஒழுங்கற்ற இதயத் துடிப்பு.',
    'after.qa4.seekList3': 'பரிந்துரைக்கப்பட்ட மருந்துகளால் கட்டுப்படுத்த முடியாத கடுமையான வலி.',
    'after.qa4.seekList4': 'அதிக இரத்தப்போக்கு அல்லது காயத்திலிருந்து நீர் வடிதல்.',
    'after.qa4.seekList5': 'தொற்றின் அறிகுறிகள் (38°C/100.4°F க்கு மேல் காய்ச்சல், அதிகரிக்கும் சிவப்பு அல்லது வெப்பம்).',
    'after.qa4.seekList6': 'அறுவை சிகிச்சைக்குப் பிறகு 8-10 மணி நேரத்திற்குள் சிறுநீர் கழிக்க முடியாமை.',
    'after.qa4.seekList7': 'தொடர்ந்து குமட்டல் மற்றும் வாந்தி.',
    'after.qa4.seekList8': 'கணுக்கால் வலி, வீக்கம் அல்லது சிவப்பு (இரத்தக் கட்டியாக இருக்கலாம்).',
    'after.qa4.pathway': '**மீட்புப் பாதை:**',
    'after.qa4.pathwayDesc': 'உங்கள் குணமடைதல் ஒரு பொதுவான முறையைப் பின்பற்றும், ஆனால் ஒவ்வொருவரும் தங்கள் சொந்த வேகத்தில் குணமடைகிறார்கள். உங்கள் உடலுடன் பொறுமையாக இருங்கள் மற்றும் சிறந்த விளைவை உறுதிசெய்ய அனைத்து மருத்துவ ஆலோசனைகளையும் பின்பற்றுங்கள்.',
    'after.qa4.keepInstructions': 'உங்கள் வெளியேற்ற வழிமுறைகளை எளிதில் அணுகக்கூடிய இடத்தில் வைத்திருங்கள் மற்றும் தொடர் பராமரிப்பு சந்திப்புகளுக்கு உங்களுடன் கொண்டு வாருங்கள்.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
  };

  // Translate function to get text for current language
  const t = (key: string): string => {
    // First try to get translation in current language
    if (translations[currentLanguage][key]) {
      return translations[currentLanguage][key];
    }
    
    // Fallback to English if translation is missing
    if (translations.en[key]) {
      return translations.en[key];
    }
    
    // Return key if no translation found
    return key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

