import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'si' | 'ta';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Basic translations object - would be expanded for a full site
const translations: Record<Language, Record<string, string>> = {
  en: {
    'site.title': 'Anaesthesia Info Hub',
    'nav.home': 'Home',
    'nav.before': 'Before Surgery',
    'nav.during': 'During Surgery',
    'nav.after': 'After Surgery',
    'nav.resources': 'Resources',
    'hero.title': 'Understanding Anaesthesia: What to Expect Before, During, and After Your Surgery',
    'hero.subtitle': 'Your guide to a safe, comfortable surgical experience',
    'hero.intro': "Anaesthesia is a medical specialty that allows you to undergo surgery pain-free and safely. Today\"s anaesthetic techniques are carefully monitored by your anaesthetist, a trained physician dedicated to your comfort and well-being.",
    'cta.before': 'Before Surgery',
    'cta.during': 'During Surgery',
    'cta.after': 'After Surgery',
    'about.title': 'About Us',
    'about.whoTitle': 'Who We Are',
    'about.who': 'A collaborative initiative by Sri Lankan anaesthesia and critical care teams to share trustworthy patient information.',
    'about.whyTitle': 'Our Mission',
    'about.why': 'To answer common patient questions, reduce anxiety, and promote informed consent.',
    
    // What to Expect Section on Home Page
    'whatToExpect.title': 'What to Expect',
    'whatToExpect.before.title': 'Before Surgery',
    'whatToExpect.before.description': 'Learn about pre-operative assessments, fasting requirements, and how to prepare mentally and physically for your procedure.',
    'whatToExpect.during.title': 'During Surgery',
    'whatToExpect.during.description': 'Discover different types of anaesthesia, how they work, potential complications, and the role of your anaesthesia team.',
    'whatToExpect.after.title': 'After Surgery',
    'whatToExpect.after.description': 'Find out what happens in the recovery room, common side effects, pain management strategies, and when you can resume normal activities.',
    'whatToExpect.learnMore': 'Learn more',
    
    // Before Surgery Page Translations
    'before.title': 'Before Surgery',
    'before.intro': 'Understanding what to expect before your procedure can help reduce anxiety and ensure the best possible outcome.',
    'before.qa1.question': 'What is pre-operative assessment?',
    'before.qa1.answer1': 'A pre-operative assessment is a thorough review of your medical history, physical examination, blood tests, ECG and other investigations to identify potential risks and optimize your health before anaesthesia.',
    'before.qa1.answer2': 'During this assessment, your anaesthetist will:',
    'before.qa1.list1': 'Review your medical history and previous surgeries',
    'before.qa1.list2': 'Ask about allergies and current medications',
    'before.qa1.list3': 'Perform a physical examination focused on your heart and lungs',
    'before.qa1.list4': 'Evaluate test results including blood work and ECG',
    'before.qa1.list5': 'Discuss the anaesthetic plan and answer your questions',
    'before.qa2.question': 'Why is fasting required?',
    'before.qa2.answer1': 'Fasting before surgery is essential to reduce the risk of stomach contents entering your lungs during anaesthesia, a serious complication called aspiration.',
    'before.qa2.guidelines': 'Fasting Guidelines:',
    'before.qa2.list1': 'Solids and milk: Stop 6 hours before surgery',
    'before.qa2.list2': 'Clear fluids (water, tea without milk): Stop 2 hours before surgery',
    'before.qa2.siptitle': 'Sip Till Send Program:',
    'before.qa2.siptext1': 'Many hospitals now encourage patients to drink clear fluids until 2 hours before surgery. This helps prevent dehydration and may improve your recovery. Ask your healthcare provider about the "Sip Till Send" protocol.',
    'before.qa2.siptext2': 'Learn more about Sip Till Send fasting information',
    'before.qa3.question': 'Which medications to avoid?',
    'before.qa3.answer1': 'Some medications can interfere with anaesthesia or increase surgical bleeding risk. Always inform your anaesthetist about all medications you\'re taking, including over-the-counter drugs and supplements.',
    'before.qa3.subtitle': 'Medications that may need to be stopped or adjusted include:',
    'before.qa3.list1': 'Blood thinners: Aspirin, clopidogrel, warfarin',
    'before.qa3.list2': 'NSAIDs: Ibuprofen, diclofenac',
    'before.qa3.list3': 'Herbal supplements: Ginkgo, garlic, fish oil',
    'before.qa3.important': 'Important: Never stop prescription medications without consulting your doctor or anaesthetist first.',
    'before.qa4.question': 'How to prepare mentally and physically?',
    'before.qa4.physical': 'Physical Preparation:',
    'before.qa4.plist1': 'Get a good night\'s sleep before surgery',
    'before.qa4.plist2': 'Stay hydrated until fasting time begins',
    'before.qa4.plist3': 'Follow any specific instructions from your surgical team',
    'before.qa4.plist4': 'Avoid alcohol for at least 24 hours before surgery',
    'before.qa4.plist5': 'If you smoke, try to quit or reduce smoking before surgery',
    'before.qa4.mental': 'Mental Preparation:',
    'before.qa4.mlist1': 'Ask questions during your pre-op assessment to address any concerns',
    'before.qa4.mlist2': 'Practice relaxation techniques like deep breathing or meditation',
    'before.qa4.mlist3': 'Bring comforting items to the hospital (within hospital guidelines)',
    'before.qa4.mlist4': 'Arrange for support from family or friends after discharge',
    'before.qa4.practical': 'Practical Preparations:',
    'before.qa4.prlist1': 'Arrange transport to and from the hospital',
    'before.qa4.prlist2': 'Prepare your home for your return (easy meals, comfortable recovery area)',
    'before.qa4.prlist3': 'Bring a list of your medications, allergies, and previous anaesthetic experiences',
    'before.qa4.prlist4': 'Remove jewelry, makeup, and nail polish before surgery',
    'before.qa4.prlist5': 'Follow specific instructions about bathing/showering before surgery',
    
    // During Surgery Translations
    'during.title': 'During Surgery',
    'during.intro': 'Understanding what happens during surgery and how anaesthesia works can help ease anxiety and prepare you for your procedure.',
    'during.qa1.question': 'What types of anaesthesia exist?',
    'during.qa1.general': 'General Anaesthesia (GA):',
    'during.qa1.generalDesc': 'A medication-induced state of unconsciousness. You\'ll be completely unaware and unable to feel pain during your procedure.',
    'during.qa1.generalUse': 'Typically used for: Major surgeries, procedures in body cavities, or when other types aren\'t suitable.',
    'during.qa1.spinal': 'Spinal/Epidural Anaesthesia:',
    'during.qa1.spinalDesc': 'Injection of local anaesthetic into the subarachnoid space (spinal) or epidural space to block nerve transmission below the waist.',
    'during.qa1.spinalUse': 'Typically used for: Lower body procedures, cesarean sections, hip/knee surgery.',
    'during.qa1.nerve': 'Peripheral Nerve Blocks:',
    'during.qa1.nerveDesc': 'Local anaesthetic injected near specific nerves to numb a particular area of the body.',
    'during.qa1.nerveUse': 'Typically used for: Arm, shoulder, or leg surgeries, providing targeted pain relief.',
    'during.qa1.sedation': 'Conscious Sedation (Monitored Anaesthesia Care):',
    'during.qa1.sedationDesc': 'Medications to help you relax and reduce pain while maintaining consciousness.',
    'during.qa1.sedationUse': 'Typically used for: Minor procedures, endoscopies, dental work.',
    
    'during.qa2.question': 'How does each type of anaesthesia work?',
    'during.qa2.general': 'General Anaesthesia Mechanics:',
    'during.qa2.generalDesc': 'General anaesthesia works through a combination of medications that:',
    'during.qa2.generalList1': 'Induce unconsciousness (propofol, thiopental)',
    'during.qa2.generalList2': 'Maintain unconsciousness (sevoflurane, desflurane gases)',
    'during.qa2.generalList3': 'Relax muscles (rocuronium, succinylcholine)',
    'during.qa2.generalList4': 'Block pain (fentanyl, morphine)',
    'during.qa2.generalEnd': 'These medications depress your central nervous system in a controlled manner, affecting different brain receptors to create a reversible state of unconsciousness.',
    'during.qa2.spinal': 'Spinal/Epidural Mechanics:',
    'during.qa2.spinalDesc': 'Local anaesthetic (like bupivacaine) is injected near the spinal cord:',
    'during.qa2.spinalList1': 'Spinal: Directly into the cerebrospinal fluid surrounding the spinal cord',
    'during.qa2.spinalList2': 'Epidural: Into the space just outside the spinal cord coverings',
    'during.qa2.spinalEnd': 'The medication blocks sodium channels in nerve membranes, preventing nerve impulses from traveling up the spinal cord to the brain.',
    'during.qa2.nerve': 'Peripheral Nerve Block Mechanics:',
    'during.qa2.nerveDesc': 'Using ultrasound guidance, anaesthetists inject local anaesthetic around specific nerve bundles. The medication temporarily blocks nerve transmission in that specific area without affecting consciousness.',
    'during.qa2.sedation': 'Sedation Mechanics:',
    'during.qa2.sedationDesc': 'Carefully titrated doses of medications like midazolam (a benzodiazepine) and fentanyl (an opioid) create a state of:',
    'during.qa2.sedationList1': 'Reduced anxiety',
    'during.qa2.sedationList2': 'Decreased pain sensation',
    'during.qa2.sedationList3': 'Amnesia (reduced memory of the procedure)',
    'during.qa2.sedationList4': 'Maintained consciousness and protective reflexes',
    
    'during.qa3.question': 'Risks & complications, prevention and management',
    'during.qa3.minor': 'Common Minor Effects:',
    'during.qa3.minorList1': 'Shivering (20%) - Prevented with warming blankets',
    'during.qa3.minorList2': 'Post-op nausea and vomiting (25%) - Managed with antiemetics like ondansetron',
    'during.qa3.minorList3': 'Sore throat (15%) - Minimized with gentle airway management',
    'during.qa3.minorList4': 'Headache (10%) - Treated with hydration and mild analgesics',
    'during.qa3.regional': 'Regional/Spinal Anaesthesia Risks:',
    'during.qa3.regionalList1': 'Post-dural puncture headache (1-2%) - Managed with hydration, caffeine, or epidural blood patch',
    'during.qa3.regionalList2': 'Transient neurological symptoms (0.5%) - Usually resolve with time',
    'during.qa3.regionalList3': 'Urinary retention - Temporary catheterization if needed',
    'during.qa3.serious': 'Serious but Rare Complications:',
    'during.qa3.seriousList1': 'Anaphylaxis (1 in 10,000) - Identified by monitoring and treated with epinephrine',
    'during.qa3.seriousList2': 'Malignant hyperthermia (< 1 in 50,000) - Genetic condition treated with dantrolene',
    'during.qa3.seriousList3': 'Permanent nerve injury (< 1 in 100,000) - Prevented by careful positioning and technique',
    'during.qa3.seriousList4': 'Awareness during general anaesthesia (< 1 in 1,000) - Monitored using BIS technology',
    'during.qa3.airway': 'Airway Complications:',
    'during.qa3.airwayList1': 'Difficult intubation (1-3%) - Managed with specialized equipment and techniques',
    'during.qa3.airwayList2': 'Aspiration (< 1%) - Prevented with fasting and rapid sequence induction',
    'during.qa3.airwayList3': 'Dental damage (< 0.5%) - Minimized with careful technique',
    'during.qa3.remember': 'Remember: Your anaesthetist is highly trained to prevent, detect, and manage these complications. The vast majority of anaesthetics are administered without any serious problems.',
    
    'during.qa4.question': 'Monitoring & safety measures',
    'during.qa4.standard': 'Standard Monitors (ASA Guidelines):',
    'during.qa4.standardList1': 'ECG - Monitors heart rate and rhythm',
    'during.qa4.standardList2': 'NIBP - Non-invasive blood pressure, typically measured every 3-5 minutes',
    'during.qa4.standardList3': 'SpO₂ - Oxygen saturation via pulse oximeter',
    'during.qa4.standardList4': 'ETCO₂ - End-tidal carbon dioxide to confirm proper breathing',
    'during.qa4.standardList5': 'Temperature - To detect and prevent hypothermia or hyperthermia',
    'during.qa4.advanced': 'Advanced Monitoring (as needed):',
    'during.qa4.advancedList1': 'Arterial line - For continuous blood pressure monitoring',
    'during.qa4.advancedList2': 'Central venous pressure - For complex cases or critically ill patients',
    'during.qa4.advancedList3': 'Neuromuscular blockade monitors - To ensure appropriate muscle relaxation',
    'during.qa4.advancedList4': 'BIS (Bispectral Index) - To monitor depth of anaesthesia',
    'during.qa4.targets': 'Normal Target Values:',
    'during.qa4.targetsList1': 'SpO₂: > 95%',
    'during.qa4.targetsList2': 'ETCO₂: 35-45 mmHg',
    'during.qa4.targetsList3': 'MAP (Mean Arterial Pressure): 65-90 mmHg',
    'during.qa4.targetsList4': 'Temperature: 36-37°C (97-99°F)',
    'during.qa4.safety': 'Safety Protocols:',
    'during.qa4.safetyList1': 'Pre-anaesthetic equipment checks using standardized checklists',
    'during.qa4.safetyList2': 'WHO Surgical Safety Checklist before incision',
    'during.qa4.safetyList3': 'Immediate access to emergency drugs and equipment',
    'during.qa4.safetyList4': 'Continuous visual and auditory alarms for vital sign deviations',
    'during.qa4.safetyList5': 'Capnography to confirm correct breathing tube placement',
    'during.qa4.modern': 'Modern anaesthesia monitoring has dramatically improved safety. Your vital signs are continuously displayed and monitored throughout your procedure by your anaesthesia team.',
    
    'during.qa5.question': 'Role of the anaesthetist during surgery',
    'during.qa5.intro': 'Your anaesthetist is a specially trained doctor who remains with you throughout your entire surgery, focusing exclusively on your safety and comfort.',
    'during.qa5.responsibilities': 'The anaesthetist\'s responsibilities include:',
    'during.qa5.respList1': 'Continuous assessment of vital signs, anaesthetic depth, pain control, and fluid status',
    'during.qa5.respList2': 'Dynamic medication adjustments throughout surgery based on your needs and surgical requirements',
    'during.qa5.respList3': 'Managing unexpected events like blood pressure changes, arrhythmias, or bleeding',
    'during.qa5.respList4': 'Coordinating with surgeons about timing, positioning, and special requirements',
    'during.qa5.respList5': 'Patient advocacy, ensuring your safety, dignity, and comfort at all times',
    'during.qa5.respList6': 'Making clinical decisions about blood transfusions, fluid management, and pain control',
    'during.qa5.team': 'Team Approach:',
    'during.qa5.teamDesc': 'Your anaesthetist often works with a team that may include:',
    'during.qa5.teamList1': 'Anaesthesia assistants or technicians',
    'during.qa5.teamList2': 'Nurse anaesthetists (in some countries)',
    'during.qa5.teamList3': 'Anaesthesia trainees under supervision',
    'during.qa5.think': 'Think of your anaesthetist as your personal "life functions manager" during surgery, constantly monitoring and adjusting to ensure your body\'s systems remain stable while you\'re unconscious or sedated.',
    
    // After Surgery Translations
    'after.title': 'After Surgery',
    'after.intro': 'Understanding what to expect after your procedure can help you prepare for recovery and recognize normal versus abnormal symptoms.',
    'after.qa1.question': 'What happens in the recovery room?',
    'after.qa1.intro': 'After your surgery, you\'ll be transferred to the Post-Anaesthesia Care Unit (PACU), also called the recovery room. This is a specialized area where you\'ll be closely monitored as you emerge from anaesthesia.',
    'after.qa1.expect': 'In the PACU, you can expect:',
    'after.qa1.monitoring': 'Continuous monitoring',
    'after.qa1.monitoringDesc': 'of your vital signs (blood pressure, heart rate, oxygen levels)',
    'after.qa1.nursing': 'One-to-one nursing care',
    'after.qa1.nursingDesc': 'until you\'re fully awake and stable',
    'after.qa1.assessments': 'Regular assessments',
    'after.qa1.assessmentsDesc': 'of your pain levels and administration of pain medication as needed',
    'after.qa1.oxygen': 'Oxygen therapy',
    'after.qa1.oxygenDesc': 'via a face mask or nasal prongs if required',
    'after.qa1.warming': 'Warming blankets',
    'after.qa1.warmingDesc': 'if you\'re cold or shivering',
    'after.qa1.iv': 'IV fluids',
    'after.qa1.ivDesc': 'until you\'re able to drink',
    'after.qa1.howLong': 'How long will I stay in recovery?',
    'after.qa1.timeFrame': 'Most patients stay in the PACU for 30 minutes to 2 hours, depending on:',
    'after.qa1.timeList1': 'The type of surgery and anaesthesia you received',
    'after.qa1.timeList2': 'How quickly you wake up and become stable',
    'after.qa1.timeList3': 'How well your pain and any nausea are controlled',
    'after.qa1.timeList4': 'If there were any complications during surgery',
    'after.qa1.transfer': 'You\'ll be transferred to a ward or discharged home once the recovery team is satisfied with your condition.',
    
    'after.qa2.question': 'Common post-op side effects & pain control',
    'after.qa2.sideEffects': 'Common Side Effects:',
    'after.qa2.throat': 'Sore throat',
    'after.qa2.throatDesc': '- From the breathing tube; usually resolves within 24-48 hours',
    'after.qa2.nausea': 'Nausea and vomiting',
    'after.qa2.nauseaDesc': '- Can be treated with anti-sickness medications',
    'after.qa2.dizziness': 'Dizziness',
    'after.qa2.dizzinessDesc': '- Often improves with gentle movement and hydration',
    'after.qa2.drowsiness': 'Drowsiness',
    'after.qa2.drowsinessDesc': '- Gradually improves as anaesthesia wears off',
    'after.qa2.shivering': 'Shivering',
    'after.qa2.shiveringDesc': '- Usually temporary; treated with warming blankets',
    'after.qa2.confusion': 'Confusion',
    'after.qa2.confusionDesc': '- More common in older adults; usually temporary',
    'after.qa2.painManagement': 'Pain Management Options:',
    'after.qa2.ivPain': 'IV pain medications',
    'after.qa2.ivPainDesc': '- Often opioids like morphine for immediate relief',
    'after.qa2.pca': 'Patient-Controlled Analgesia (PCA)',
    'after.qa2.pcaDesc': '- Allows you to self-administer small doses of pain medication by pressing a button',
    'after.qa2.oral': 'Oral pain medications',
    'after.qa2.oralDesc': '- Pills or liquids once you can drink fluids',
    'after.qa2.blocks': 'Regional blocks',
    'after.qa2.blocksDesc': '- May continue to provide pain relief for hours after surgery',
    'after.qa2.local': 'Local anaesthetic infiltration',
    'after.qa2.localDesc': '- Injected around the surgical site',
    'after.qa2.nonMed': 'Non-medication techniques',
    'after.qa2.nonMedDesc': '- Ice packs, positioning, relaxation techniques',
    'after.qa2.tips': 'Important Pain Management Tips:',
    'after.qa2.tipsList1': 'Don\'t wait until pain is severe before requesting pain relief',
    'after.qa2.tipsList2': 'Rate your pain on a scale from 0-10 when asked by healthcare staff',
    'after.qa2.tipsList3': 'Tell your nurses if pain medication isn\'t working or wears off quickly',
    'after.qa2.tipsList4': 'Report any unusual symptoms or side effects from pain medications',
    
    'after.qa3.question': 'When can I eat and drink?',
    'after.qa3.intro': 'Returning to eating and drinking after surgery depends on several factors including the type of surgery, anaesthesia used, and your individual recovery.',
    'after.qa3.guidelines': 'General Guidelines:',
    'after.qa3.fluids': 'Clear fluids',
    'after.qa3.fluidsDesc': '(water, apple juice) - Often allowed within 2-4 hours after fully waking from anaesthesia, once you can swallow safely',
    'after.qa3.light': 'Light foods',
    'after.qa3.lightDesc': '(crackers, toast, soup) - Usually permitted once you\'re tolerating fluids well, often 4-6 hours after surgery',
    'after.qa3.regular': 'Regular diet',
    'after.qa3.regularDesc': '- Typically resumed gradually as tolerated, often by the next day for minor surgeries',
    'after.qa3.considerations': 'Special Considerations:',
    'after.qa3.abdominal': 'Abdominal surgery',
    'after.qa3.abdominalDesc': '- May require waiting until bowel sounds return and gas or bowel movements occur',
    'after.qa3.throat': 'Throat or mouth surgery',
    'after.qa3.throatDesc': '- May require special dietary restrictions',
    'after.qa3.nausea': 'Nausea or vomiting',
    'after.qa3.nauseaDesc': '- May delay return to eating until symptoms improve',
    'after.qa3.medications': 'Some medications',
    'after.qa3.medicationsDesc': '- May need to be taken with food, affecting when you can restart them',
    'after.qa3.always': 'Always follow your healthcare provider\'s specific instructions about eating and drinking after your procedure. Start slowly and increase gradually as tolerated.',
    
    'after.qa4.question': 'Discharge instructions & follow-up',
    'after.qa4.instructions': 'Common Discharge Instructions:',
    'after.qa4.activity': 'Activity restrictions',
    'after.qa4.activityDesc': '- When you can return to normal activities, driving, work, and exercise',
    'after.qa4.wound': 'Wound care',
    'after.qa4.woundDesc': '- How to clean and dress the surgical site',
    'after.qa4.medication': 'Medication instructions',
    'after.qa4.medicationDesc': '- When and how to take prescribed medications',
    'after.qa4.infection': 'Signs of infection',
    'after.qa4.infectionDesc': '- What to watch for (increased pain, redness, swelling, discharge, fever)',
    'after.qa4.diet': 'Diet guidelines',
    'after.qa4.dietDesc': '- Any special dietary requirements during recovery',
    'after.qa4.showering': 'Showering/bathing',
    'after.qa4.showeringDesc': '- When it\'s safe to get the surgical area wet',
    'after.qa4.contact': 'Contact information',
    'after.qa4.contactDesc': '- Who to call if you have questions or problems',
    'after.qa4.appointments': 'Follow-up Appointments:',
    'after.qa4.appointmentsDesc': 'Your discharge instructions will include details about follow-up visits. Typically, you\'ll have:',
    'after.qa4.appointmentsList1': 'An appointment with your surgeon to check your healing',
    'after.qa4.appointmentsList2': 'Instructions for any suture or staple removal',
    'after.qa4.appointmentsList3': 'Information about any required physical therapy',
    'after.qa4.keepAppts': 'Be sure to keep all follow-up appointments, even if you\'re feeling well.',
    'after.qa4.seekHelp': 'When to Seek Immediate Medical Attention:',
    'after.qa4.seekList1': 'Difficulty breathing or shortness of breath',
    'after.qa4.seekList2': 'Chest pain or irregular heartbeat',
    'after.qa4.seekList3': 'Severe pain not controlled by prescribed medications',
    'after.qa4.seekList4': 'Excessive bleeding or wound drainage',
    'after.qa4.seekList5': 'Signs of infection (fever above 38°C/100.4°F, increasing redness or warmth)',
    'after.qa4.seekList6': 'Inability to urinate within 8-10 hours after surgery',
    'after.qa4.seekList7': 'Persistent nausea and vomiting',
    'after.qa4.seekList8': 'Calf pain, swelling, or redness (possible blood clot)',
    'after.qa4.pathway': 'Recovery Pathway:',
    'after.qa4.pathwayDesc': 'Your recovery will follow a general pattern, but everyone heals at their own pace. Be patient with your body and follow all medical advice to ensure the best outcome.',
    'after.qa4.keepInstructions': 'Keep your discharge instructions in an easily accessible place and bring them with you to follow-up appointments.'
  },
  si: {
    
    'site.title': 'නිර්වේදන තොරතුරු මධ්‍යස්ථානය',
    'nav.home': 'මුල් පිටුව',
    'nav.before': 'ශල්‍යකර්මයට පෙර',
    'nav.during': 'ශල්‍යකර්මය අතරතුර',
    'nav.after': 'ශල්‍යකර්මයෙන් පසු',
    'nav.resources': 'සම්පත්',
    'hero.title': 'නිර්වේදනය ගැන අවබෝධ කර ගැනීම: ඔබේ ශල්‍යකර්මයට පෙර, අතරතුර සහ පසුව බලාපොරොත්තු විය හැකි දේ',
    'hero.subtitle': 'ආරක්ෂිත, පහසු ශල්‍යකර්ම අත්දැකීමක් සඳහා ඔබේ මාර්ගෝපදේශය',
    'hero.intro': "නිර්වේදනය යනු ඔබට වේදනාවෙන් තොරව සහ ආරක්ෂිතව ශල්‍යකර්මයකට භාජනය වීමට ඉඩ සලසන වෛද්‍ය විශේෂතාවකි. අද දින නිර්වේදන තාක්ෂණයන් ඔබේ සුවපහසුව සහ යහපැවැත්ම සඳහා කැපවූ පුහුණු වෛද්‍යවරයෙකු වන ඔබේ නිර්වේදකයා විසින් සාවධානව නිරීක්ෂණය කරනු ලැබේ.",
    'cta.before': 'ශල්‍යකර්මයට පෙර',
    'cta.during': 'ශල්‍යකර්මය අතරතුර',
    'cta.after': 'ශල්‍යකර්මයෙන් පසු',
    'about.title': 'අප ගැන',
    'about.whoTitle': 'අපි කවුද',
    'about.who': 'විශ්වාසදායක රෝගී තොරතුරු බෙදා ගැනීම සඳහා ශ්‍රී ලාංකික නිර්වේදන හා දැඩි සත්කාර කණ්ඩායම් විසින් සිදු කරන සහයෝගී මුල පිරීමකි.',
    'about.whyTitle': 'අපේ දැක්ම',
    'about.why': 'පොදු රෝගී ප්‍රශ්න වලට පිළිතුරු දීමට, කනස්සල්ල අඩු කිරීමට සහ දැනුවත් කැමැත්ත ප්‍රවර්ධනය කිරීමට.',
    
    // What to Expect Section on Home Page - Sinhala
    'whatToExpect.title': 'බලාපොරොත්තු විය හැකි දේ',
    'whatToExpect.before.title': 'ශල්‍යකර්මයට පෙර',
    'whatToExpect.before.description': 'ශල්‍යකර්මයට පෙර ඇගයීම්, උපවාසය අවශ්‍යතා, සහ මානසිකව හා ශාරීරිකව සූදානම් වන්නේ කෙසේද යන්න ගැන ඉගෙන ගන්න.',
    'whatToExpect.during.title': 'ශල්‍යකර්මය අතරතුර',
    'whatToExpect.during.description': 'විවිධ වර්ගයේ නිර්වින්දනයන්, ඒවා ක්‍රියාත්මක වන ආකාරය, විය හැකි සංකූලතා, සහ ඔබේ නිර්වින්දන කණ්ඩායමේ භූමිකාව ගැන සොයාගන්න.',
    'whatToExpect.after.title': 'ශල්‍යකර්මයෙන් පසු',
    'whatToExpect.after.description': 'ප්‍රකෘතිමත් වීමේ කාමරයේ සිදුවන දේ, පොදු අතුරු ආබාධ, වේදනා කළමනාකරණ උපාය මාර්ග සහ සාමාන්‍ය ක්‍රියාකාරකම් නැවත ආරම්භ කළ හැකි අවස්ථාව ගැන සොයා ගන්න.',
    'whatToExpect.learnMore': 'වැඩි විස්තර ඒ',
    
    // Before Surgery Page Translations - Already defined
    'before.title': 'ශල්‍යකර්මයට පෙර',
    'before.intro': 'ඔබේ ක්‍රියාපටිපාටියට පෙර බලාපොරොත්තු විය හැකි දේ ගැන අවබෝධයක් ලබා ගැනීමෙන් කනස්සල්ල අඩු කිරීමට සහ හැකි උපරිම ප්‍රතිඵලයක් සහතික කිරීමට උපකාරී විය හැක.',
    'before.qa1.question': 'ශල්‍යකර්මයට පෙර ඇගයීම යනු කුමක්ද?',
    'before.qa1.answer1': 'නිර්වේදනයට පෙර අවදානම් හඳුනා ගැනීම සහ ඔබේ සෞඛ්‍යය වැඩිදියුණු කිරීම සඳහා ඔබේ වෛද්‍ය ඉතිහාසය, ශාරීරික පරීක්ෂණය, රුධිර පරීක්ෂණ, ECG සහ වෙනත් පරීක්ෂණ පිළිබඳ සවිස්තරාත්මක සමාලෝචනයකි.',
    'before.qa1.answer2': 'මෙම තක්සේරුව අතරතුර, ඔබේ නිර්වේදකයා:',
    'before.qa1.list1': 'ඔබේ වෛද්‍ය ඉතිහාසය සහ පෙර ශල්‍යකර්ම සමාලෝචනය කරනු ඇත',
    'before.qa1.list2': 'ඇලජි සහ වත්මන් ඖෂධ ගැන විමසනු ඇත',
    'before.qa1.list3': 'ඔබේ හෘදය සහ පෙනහළු කේන්ද්‍ර කර ගත් ශාරීරික පරීක්ෂණයක් සිදු කරනු ඇත',
    'before.qa1.list4': 'රුධිර පරීක්ෂණ සහ ECG ඇතුළු පරීක්ෂණ ප්‍රතිඵල ඇගයීම කරනු ඇත',
    'before.qa1.list5': 'නිර්වේදන සැලැස්ම සාකච්ඡා කර ඔබේ ප්‍රශ්නවලට පිළිතුරු දෙනු ඇත',
    'before.qa2.question': 'උපවාසය අවශ්‍ය වන්නේ ඇයි?',
    'before.qa2.answer1': 'නිර්වේදනය අතරතුර ඔබේ ආමාශයේ අඩංගු දේ ඔබේ පෙනහළු වලට ඇතුළු වීමේ අවදානම අඩු කිරීම සඳහා ශල්‍යකර්මයට පෙර උපවාසය අත්‍යවශ්‍ය වේ, එය aspiration නම් බරපතල සංකූලතාවයකි.',
    'before.qa2.guidelines': 'උපවාස මාර්ගෝපදේශ:',
    'before.qa2.list1': 'ඝන ආහාර සහ කිරි: ශල්‍යකර්මයට පැය 6කට පෙර නවත්වන්න',
    'before.qa2.list2': 'පැහැදිලි ද්‍රව (ජලය, කිරි නොමැති තේ): ශල්‍යකර්මයට පැය 2කට පෙර නවත්වන්න',
    'before.qa2.siptitle': 'සිප් ටිල් සෙන්ඩ් වැඩසටහන:',
    'before.qa2.siptext1': 'බොහෝ රෝහල් දැන් ශල්‍යකර්මයට පැය 2කට පෙර තෙක් පැහැදිලි ද්‍රව පානය කිරීමට රෝගීන් දිරිමත් කරයි. මෙය ජල විරහිත වීම වැළැක්වීමට උපකාරී වන අතර ඔබේ සුවය වැඩිදියුණු කළ හැක. "සිප් ටිල් සෙන්ඩ්" ක්‍රමලේඛය ගැන ඔබේ සෞඛ්‍ය සේවා සපයන්නාගෙන් විමසන්න.',
    'before.qa2.siptext2': 'සිප් ටිල් සෙන්ඩ් උපවාස තොරතුරු ගැන වැඩිදුර දැනගන්න',
    'before.qa3.question': 'මඟ හැරිය යුතු ඖෂධ මොනවාද?',
    'before.qa3.answer1': 'සමහර ඖෂධ නිර්වේදනයට බාධා කළ හැකි හෝ ශල්‍යකර්ම ලේ ගැලීමේ අවදානම වැඩි කළ හැකිය. ඔබ ගන්නා සිය
